### ISSUE TITLE
Stuck magento ver. 1.9.3.2

### ISSUE THREAD

**Issue by victooooor** [magenx/Magento-Automated-Server-Configuration-from-MagenX#113]
Hello!

I loved your script, but i have problem final setup. All done ok, please check link,  can't continue, can help why ?
http://www.oficiall.com.br/

**Comment by magenx** [comment]
web installation wizard is not a part of this script.
installation done in command line, automatically.

**Comment by victooooor** [comment]
I thought the same thing!
I completed the entire script successfully.
In the end, when I received notice to access the site, I had this surpise.

**Comment by magenx** [comment]
looking at your previous messages looks like you do something wrong from the start
