### ISSUE TITLE
just bug

### ISSUE THREAD

**Issue by grzegorz77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#114]
centOS7 min updated
script v "20.4.2"

Magento-Automated-Server-Configuration-from-MagenX/Magento-2/CentOS-7/MASC-M-7-v2.sh: line 1242: bin/magento: No such file or directory

**Comment by magenx** [comment]
thank you 
forgot to include path to bin/magento

fixed

**Comment by grzegorz77** [comment]
centOS7 min updated
script v "20.4.2"
------------------------------------------------------------------------------------
| POST-INSTALLATION CONFIGURATION |
-------------------------------------------------------------------------------------


		SERVER TIMEZONE SETTINGS

		HHVM AND PHP-FPM SETTINGS

		NGINX SETTINGS
sed: -e expression #1, char 20: unterminated `s' command

		PHPMYADMIN INSTALLATION AND CONFIGURATION

**Comment by magenx** [comment]
fixed now
it replaces `ADMIN_PLACEHOLDER` in /etc/nginx/conf_m2/extra_protect.conf
with your real admin path name

thank you
