### ISSUE TITLE
Composer issue When Selecting Magento 2

### ISSUE THREAD

**Issue by skmudabbir** [magenx/Magento-Automated-Server-Configuration-from-MagenX#115]
Hello

This issue occurs when composer is giving error when we select from the menu magento > Select Magento 2, It says it will be downloaded to newly created user home directory and then throws error >
bash: composer: command not found
When installing composer it creates a file(composer) not a directory under /usr/local/bin/, it does not move composer.phar to the location.and there when we do manual install of composer it gives error
COMPOSER INSTALLATION ERROR

When we ignore this and go to next steps the above bad array subscript error comes.

**Comment by skmudabbir** [comment]
I tried this script again on Centos 7 and when on Magento Step it gives this error again

 SELECT TO DOWNLOAD MAGENTO 1 (1.9.3.4) OR 2 (2.2.0-RC1.6) |
-------------------------------------------------------------------------------------


---> SELECT MAGENTO TO DOWNLOAD 1 OR 2: 2

---> ENTER YOUR DOMAIN NAME OR IP ADDRESS: example.com
---> ENTER MAGENTO / FTP USER NAME: exampleuser

---> MAGENTO 2 (2.2.0-RC1.6)
---> WILL BE DOWNLOADED TO /home/exampleuser/public_html


bash: composer: command not found


		=============================================================================
		== MAGENTO DOWNLOADED AND READY FOR INSTALLATION ==
		=============================================================================

------> Press [Enter] key to show menu

**Comment by devneri** [comment]
Same issue for me, but I resolved reading this:

https://www.smartiehastheanswer.co.uk/magento2/creating-a-magento2-project-with-composer.html

So you have to create an access key pair (composed by a public key and a private key) in your magento.com account dashboard and use them respectively as a username and password when requested.

**Comment by serblama** [comment]
i have the same problem

**Comment by corpsysgit** [comment]
Quit script execution and install the composer:

https://www.vultr.com/docs/install-composer-on-centos-7
