### ISSUE TITLE
nginx: [emerg] invalid parameter "/32" in /etc/nginx/conf_m2/phpmyadmin.conf:6

### ISSUE THREAD

**Issue by gsdsd** [magenx/Magento-Automated-Server-Configuration-from-MagenX#116]
Ok it seems that I have the same error message as the user above and I put this comment because you have closed this ticket without giving a public solution.

> nginx: [emerg] invalid parameter "/32" in /etc/nginx/conf_m2/phpmyadmin.conf:6

VM Virtualized with LibVirt on Ubuntu 14:

>  CentOS Linux release 7.3.1611 (Core)

SSH:

> OpenSSH_6.6.1p1
> OpenSSL 1.0.1e-fips 

Regards,

GsdSd

**Comment by gsdsd** [comment]
Ok, error resolved, missing the ip address in front of  / 32 (probably due to the installation on a VM).

Comment on the script:
Very complete, there is almost nothing besides the verification of the presence of the required packages, such as:

> rpm -qa | grep -qw perl-devel || yum install perl-devel
> rpm -qa | grep -qw expect || yum install expect
> rpm -qa | grep -qw perl-DBD || yum install "perl(DBD::mysql)"
> rpm -qa | grep -qw perl-DBI || yum install "perl(DBD::mysql)"

Concerning SELINUX, as the script is executed in ROOT why not add the following two lines to disable it:

> setenforce 0
> sed -i "s/SELINUX=.*/SELINUX=disabled/" /etc/sysconfig/selinux

Another error was encountered when downloading the JDK, the wget link is broken, I had to install it by hand.

It also lacks the following parameters in the file nginx.conf:

> map_hash_max_size 262144;
> map_hash_bucket_size 262144;
> server_names_hash_bucket_size 

Regards,

GsdSd

**Comment by magenx** [comment]
yes ip address is taken from ${SSH_CLIENT}, but looks like in your case it was empty.
firewalld is better to replace with csf firewall.

**Comment by gsdsd** [comment]
I installed from the virt-manager interface (libvirt), no installation with ssh, so no $ {SSH_CLIENT} variable, check if this variable is empty and if not propose to write an IP address.

At the end of the script execution, CSF is not enabled and ports 443 and 80 are not accessible.

>                                          /-------> VM Centreon/Nagios ------------------\\
> IP External <- | -> VM Firewall <-> VM Internal Proxy with Cache <-> VM Magento Dev (Centos)
>                                            \ ------> VM Percona SQL <------------------- /

Regards,

GsdSd
