### ISSUE TITLE
sed: can't read /etc/hhvm/server.ini: No such file or directory

### ISSUE THREAD

**Issue by agunes77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#120]
config
-------------------------------------------------------------------------------------
| POST-INSTALLATION CONFIGURATION |
-------------------------------------------------------------------------------------

                SERVER HOSTNAME SETTINGS

                SERVER TIMEZONE SETTINGS

                HHVM AND PHP-FPM SETTINGS
sed: can't read /etc/hhvm/server.ini: No such file or directory
sed: can't read /etc/hhvm/server.ini: No such file or directory

                NGINX SETTINGS

                PHPMYADMIN INSTALLATION AND CONFIGURATION

                PROFTPD CONFIGURATION

**Comment by magenx** [comment]
yes server.ini file was missing
