### ISSUE TITLE
Menu "Config"  errors

### ISSUE THREAD

**Issue by agunes77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#122]
config
-------------------------------------------------------------------------------------
| POST-INSTALLATION CONFIGURATION |
-------------------------------------------------------------------------------------

                SERVER HOSTNAME SETTINGS

                SERVER TIMEZONE SETTINGS
Invalid number of arguments.

                HHVM AND PHP-FPM SETTINGS
sed: -e expression #1, char 51: unterminated `s' command

                NGINX SETTINGS

                PHPMYADMIN INSTALLATION AND CONFIGURATION
http://ftp.arnes.si/mirrors/remi/enterprise/7/remi/x86_64/php-symfony3-cache-3.2.13-1.el7.remi.noarch.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

                PROFTPD CONFIGURATION

                VARNISH CACHE SETTINGS
                VARNISH CACHE PORT :8081

                OPCACHE GUI, n98-MAGERUN, IMAGE OPTIMIZER, MYSQLTUNER, SSL DEBUG TOOLS

                SYSTEM AUTO UPDATE WITH YUM-CRON
sed: -e expression #1, char 50: unterminated `s' command

                LETSENCRYPT SSL CERTIFICATE REQUEST

                DNS A record and your servers IP address do not match
                Your servers ip address 192.168.1.10
                Domain myshop.com resolves to 85.105.56.46
                Please change your DNS A record to this servers IP address, and run this command later:
                /usr/bin/certbot certonly --agree-tos --email admin@myshop.com information --webroot -w /home/myshop/public_html -d nealirsanal.com -d www.nealirsanal.com

                GENERATE DHPARAM FOR NGINX SSL
Generating DSA parameters, 4096 bit long prime
..+.............+...+....+......+.+....+.+.....+....+.....+...............+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*
.+......+......+......+.....................+...+............+...............+....+.....+..+..+....+....+......+...........................+..............................+..............+.+....................................+.......+...+.......+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*

                GENERATE DEFAULT NGINX SSL SERVER KEY/CERT
Generating a 4096 bit RSA private key
..................................................................................................++
............++
writing new private key to '/etc/ssl/certs/default_server.key'
-----

                SIMPLE LOGROTATE SCRIPT FOR MAGENTO LOGS

                SERVICE STATUS WITH E-MAIL ALERTING
sed: -e expression #1, char 38: unterminated `s' command

                REALTIME MALWARE MONITOR WITH E-MAIL ALERTING
                warning: infected files will be moved to quarantine
Cloning into 'linux-malware-detect'...
remote: Counting objects: 1592, done.
remote: Total 1592 (delta 0), reused 0 (delta 0), pack-reused 1592
Receiving objects: 100% (1592/1592), 1.59 MiB | 639.00 KiB/s, done.
Resolving deltas: 100% (1164/1164), done.
sed: -e expression #1, char 38: unterminated `s' command

                GOACCESS REALTIME ACCESS LOG DASHBOARD
Cloning into 'goaccess'...
remote: Counting objects: 10642, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 10642 (delta 4), reused 7 (delta 2), pack-reused 10633
Receiving objects: 100% (10642/10642), 4.39 MiB | 920.00 KiB/s, done.
Resolving deltas: 100% (7320/7320), done.
Copying file ABOUT-NLS
Copying file config.rpath
Creating directory m4
Copying file m4/codeset.m4
Copying file m4/fcntl-o.m4
Copying file m4/gettext.m4
Copying file m4/glibc2.m4
Copying file m4/glibc21.m4
Copying file m4/iconv.m4
Copying file m4/intdiv0.m4
Copying file m4/intl.m4
Copying file m4/intldir.m4
Copying file m4/intlmacosx.m4
Copying file m4/intmax.m4
Copying file m4/inttypes-pri.m4
Copying file m4/inttypes_h.m4
Copying file m4/lcmessage.m4
Copying file m4/lib-ld.m4
Copying file m4/lib-link.m4
Copying file m4/lib-prefix.m4
Copying file m4/lock.m4
Copying file m4/longlong.m4
Copying file m4/nls.m4
Copying file m4/po.m4
Copying file m4/printf-posix.m4
Copying file m4/progtest.m4
Copying file m4/size_max.m4
Copying file m4/stdint_h.m4
Copying file m4/threadlib.m4
Copying file m4/uintmax_t.m4
Copying file m4/visibility.m4
Copying file m4/wchar_t.m4
Copying file m4/wint_t.m4
Copying file m4/xsize.m4
Copying file po/Makefile.in.in
Copying file po/Makevars.template
Copying file po/Rules-quot
Copying file po/boldquot.sed
Copying file po/en@boldquot.header
Copying file po/en@quot.header
Copying file po/insert-header.sin
Copying file po/quot.sed
Copying file po/remove-potcdate.sin
configure.ac:20: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:20: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:20: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:18: installing './compile'
configure.ac:20: installing './config.guess'
configure.ac:20: installing './config.sub'
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './depcomp'

                MAGENTO CRONJOBS
"magecron":2: bad minute
errors in crontab file, can't install.

                REDIS CACHE AND SESSION STORAGE

                DISABLE MAGENTO DATABASE LOGGING

Job for php-fpm.service failed because the control process exited with error code. See "systemctl status php-fpm.service" and "journalctl -xe" for details.
                OPCACHE INVALIDATION MONITOR

                CLEANING UP INDEXES LOCKS AND RUNNING RE-INDEX ALL

Product Attributes index was rebuilt successfully in 00:00:00
Product Prices index was rebuilt successfully in 00:00:00
Catalog URL Rewrites index was rebuilt successfully in 00:00:00
Product Flat Data index was rebuilt successfully in 00:00:00
Category Flat Data index was rebuilt successfully in 00:00:00
Category Products index was rebuilt successfully in 00:00:00
Catalog Search Index index was rebuilt successfully in 00:00:00
Stock Status index was rebuilt successfully in 00:00:00
Tag Aggregation Data index was rebuilt successfully in 00:00:00

                IMAGES OPTIMIZATION SCRIPT

                FIXING PERMISSIONS

===========================  INSTALLATION LOG  ======================================

                [shop domain]: myshop.com
                [webroot path]: /home/myshop/public_html
                [admin path]: myshop.com/admin_kEmJqp
                [admin name]: admin admin
                [admin pass]: S3NuYF9tnZ25627 Database

                [phpmyadmin url]: myshop.com/mysql_ChGcWS
                [phpmyadmin http auth name]: mysql
                [phpmyadmin http auth pass]: PjFrtO

                [mysql host]: localhost admin
                [mysql user]: m1u_8df9_170803 information
                [mysql pass]: ZfdfxAznan05Zxp nwQ2YAJe0J25629--->
                [mysql database]: m1d_1051_170803 Database
                [mysql root pass]: 6gFYTnKlJSTy6US Enter

                [ftp port]: 5123
                [ftp user]: myshop
                [ftp password]: 7uNHolHojCV6Uy7
                [ftp geoip]: IP
                [ftp ip login]: 192.168.1.2

                [opcache gui]: PizqdOqsXQuT_opcache_gui.php

===========================  INSTALLATION LOG  ======================================

-------------------------------------------------------------------------------------
| POST-INSTALLATION CONFIGURATION IS COMPLETED |
-------------------------------------------------------------------------------------

---> Press [Enter] key to show menu

**Comment by magenx** [comment]
looks like something wrong with installation order
or missing variable.

**Comment by agunes77** [comment]
Thank you magenx 
Now very good work

Sincerely
