### ISSUE TITLE
PhpMyAdmin link don't open

### ISSUE THREAD

**Issue by agunes77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#124]
===========================  INSTALLATION LOG  ======================================

                [shop domain]: myshop.com
                [webroot path]: /home/myshop/public_html
                [admin path]: myshop.com/admin_hezDjf
                [admin name]: admin
                [admin pass]: FAGEwyVKw312216

                **[phpmyadmin url]: myshop.com/mysql_NnD3gJ
                [phpmyadmin http auth name]: mysql
                [phpmyadmin http auth pass]: mviYL3**

                [mysql host]: localhost
                [mysql user]: m1u_a66b_170804
                [mysql pass]: GxycIf36KVJ17bb
                [mysql database]: m1d_8115_170804
                [mysql root pass]: 7L523MCRPV8chOb

                [ftp port]: 5123
                [ftp user]: myshop
                [ftp password]: GGcwMRFX0DJn6Kd
                [ftp geoip]: IP
                [ftp ip login]: 192.168.1.2

                [opcache gui]: FaRiLaxWaqZd_opcache_gui.php

**Comment by agunes77** [comment]
[2017-08-10_13-53-56.pdf](https://github.com/magenx/Magento-Automated-Server-Configuration-from-MagenX/files/1214637/2017-08-10_13-53-56.pdf)

**Comment by magenx** [comment]
inthis file:
`conf_m1/extra_protect.conf`

at line 17

youcanadd location:
**mysql_NnD3gJ**

**Comment by agunes77** [comment]
Thank you
