### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by corpsysgit** [magenx/Magento-Automated-Server-Configuration-from-MagenX#128]
I activated ssl and took the # from port line 443 in /etc/nginx/sites-enabled/magento2.conf

And the page does not open and the following error occurs:

ERR_TOO_MANY_REDIRECTS

**Comment by gladroger** [comment]
Steps to get SSL working after installation.
1. Run `certbot - /usr/bin/certbot certonly --agree-tos --email myemail@domain.com --webroot -w /home/user /public_html/pub -d domain.com -d www.domain.com*
2. Go to ssh  and go to /home/**user**/public/html and run `php bin/magento setup:store-config:set --base-url-secure="https://domain.com/"`
3. Remove comments # from /etc/nginx/sites-enabled/magento2.conf
server {
        listen 80 reuseport;
	**listen 443 ssl http2 reuseport;** 
	server_name domain.com;
**ssl_certificate     /etc/letsencrypt/live/domain.com/fullchain.pem;  
ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;**

4. Remove comments # from all SSL settings /etc/nginx/nginx.conf 
    #ssl_session_cache		shared:SSL:45m;
    #ssl_session_timeout	15m;
    #ssl_protocols		TLSv1.1 TLSv1.2;
    #ssl_ciphers                "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!3DES:!aNULL:!MD5";
    #ssl_prefer_server_ciphers	on;
    #ssl_dhparam 		/etc/ssl/certs/dhparams.pem;
    #ssl_ecdh_curve		secp384r1;
    #ssl_buffer_size		4k;
    
    #ssl_stapling on;
    #ssl_trusted_certificate	/etc/letsencrypt/live/domain.com/chain.pem;
    #resolver 8.8.8.8 8.8.4.4 valid=3600s;
    #resolver_timeout 5s;
5.  Run `sudo rm -rf var/cache var/generation var/page_cache` in /home/user/public_html

6. Restart Nginx, `service nginx restart`

Now it should work, if not, try to clear cookies and cache in your browser, also clear HSTS.

**Comment by corpsysgit** [comment]
yes , i resolved
