### ISSUE TITLE
hhvm start failed

### ISSUE THREAD

**Issue by sinamiandashti** [magenx/Magento-Automated-Server-Configuration-from-MagenX#130]
[Fri Aug 18 14:18:22 2017] [hphp] [6079:7f235bac7340:0:000001] [] BootStats: mapping self...
[Fri Aug 18 14:18:22 2017] [hphp] [6079:7f235bac7340:0:000002] [] BootStats: mapping self block done, took 2ms wall, 2ms cpu, 0 MB RSS
[Fri Aug 18 14:18:22 2017] [hphp] [6079:7f235bac7340:0:000003] [] BootStats: pagein_self done, took 2ms wall, 2ms cpu, 0 MB RSS
[Fri Aug 18 14:18:22 2017] [hphp] [6079:7f235bac7340:0:000004] [] cap_set_proc failed: Operation not permitted

**Comment by magenx** [comment]
user/group change
