### ISSUE TITLE
Can't enable cache and can't mark/delete inbox messages

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-Automated-Server-Configuration-from-MagenX#132]
Hi, I have magento m1 with centos 7. when I try to enable caching on System > Cache Management I see only reload page without any changes.

In 'Messages' I can't mark all messages as read or delete it. Only with click on 'remove' on each message. 

How I can solve that problem? Thank you.

UPDATE: Magento can't save values from admin panel to database.

**Comment by magenx** [comment]
make sure you have admin path the same in:
https://github.com/magenx/Magento-nginx-config/blob/master/magento1/conf_m1/extra_protect.conf#L17

**Comment by skazhikadyadya** [comment]
Thank you.
