### ISSUE TITLE
Can't login to adminpanel in Chrome and Firefox

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-Automated-Server-Configuration-from-MagenX#133]
Magento 1, CentOS 7, default script installation.

system.log:
`2017-08-31T18:15:59+00:00 ERR (3): Recoverable Error: session_regenerate_id(): Failed to create(read) session ID: user (path: tcp://127.0.0.1:6379)  in /home/myshop/public_html/app/code/core/Mage/Core/Model/Session/Abstract/Varien.php on line 514`

**Comment by magenx** [comment]
maybe something here
https://github.com/Inchoo/Inchoo_PHP7/issues/4

**Comment by skazhikadyadya** [comment]
Thanks.
