### ISSUE TITLE
How I can use images optimization script

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-Automated-Server-Configuration-from-MagenX#134]
Hi, when i try to run manually `sh ./optimages.sh` I see error
`Couldn't watch /home/myshop/public_html/var/media: No such file or directory`

If i change path in script to `/home/myshop/public_html/media` and run - I see nothing. 

How I can optimize our images in ./media and ./skin? 

Thank you.

**Comment by magenx** [comment]
it looks like this script is only configured for Magento 2.
need to change path.

for Magento 1 it will be without **pub/**

https://github.com/magenx/Magento-Automated-Server-Configuration-from-MagenX/blob/master/Magento-2/CentOS-7/MASC-M-7-v2.sh#L1672

**Comment by skazhikadyadya** [comment]
OK, thank you, can I optimize my existing images in media with that script? 




On Thu, Aug 31, 2017 at 10:06 PM +0300, "MagenX" <notifications@github.com> wrote:












it looks like this script is only configured for Magento 2.

need to change path.


for Magento 1 it will be without pub/


https://github.com/magenx/Magento-Automated-Server-Configuration-from-MagenX/blob/master/Magento-2/CentOS-7/MASC-M-7-v2.sh#L1672

**Comment by magenx** [comment]
you can run also **wesley.pl** directly

**Comment by skazhikadyadya** [comment]
Thank you, it works fine.
