### ISSUE TITLE
Ossec installation

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#139]
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.6.0]; found [5.5.2]"
Created symlink from /etc/systemd/system/multi-user.target.wants/kibana.service to /etc/systemd/system/kibana.service.
./MASC-M-7-v2.sh: line 1986: GREETXT: command not found
Redirecting to /bin/systemctl reload  nginx.service
                KIBANA WEB INTERFACE PORT: 10517
                KIBANA HTTP AUTH: wazuh-web 
                WAZUH API AUTH: wazuh-api

**Comment by magenx** [comment]
plugin was fixed now,
5.6.0

Install the Wazuh App plugin for Kibana:
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip

**Comment by gladroger** [comment]
Great, can confirm it is working! Thanks
