### ISSUE TITLE
Varnish Cache Settings fails

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#140]
During config, everything up till this point has been smoothly. 
VARNISH CACHE SETTINGS
Job for varnish.service failed because the control process exited with error code. See "systemctl status varnish.service" and "journalctl -xe" for details.
VARNISH CACHE PORT :8081

**Comment by gladroger** [comment]
varnishlog
Can't open VSM file (Cannot open /var/lib/varnish/my.mysite.com/_.vsm: No such file or directory

**Comment by magenx** [comment]
make sure that path is correct??

**Comment by gladroger** [comment]
varnishlog
Can't open VSM file (Cannot open /var/lib/varnish/my.mysite.com/_.vsm: No such file or directory
)

[root@dw ~]# cd /var/lib/varnish/my.mysite.com/

[root@dw my.mysite.com]# ls


[root@dw my.mysite.com]# stat /var/lib/varnish/my.mysite.com/
  File: ‘/var/lib/varnish/my.mysite.com/’
  Size: 6               Blocks: 0          IO Block: 4096   directory
Device: fd00h/64768d    Inode: 34698266    Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-09-13 11:32:53.852978987 +0200
Modify: 2017-09-13 11:32:54.100978984 +0200
Change: 2017-09-13 11:32:54.100978984 +0200
 Birth: -`

**Comment by gladroger** [comment]
tested to change directory to 777 and varnish starts.

**Comment by magenx** [comment]
then permissions

**Comment by gladroger** [comment]
Yes, I checked the folder and as above it's 755 and owned by root/root
