### ISSUE TITLE
Mysqld.service restarts

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#141]
`Status report for unit: mysqld.service

â— mysqld.service - MySQL Percona Server
   Loaded: loaded (/etc/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-09-15 15:21:16 CEST; 7ms ago
  Process: 8738 ExecStartPost=/usr/bin/mysql-systemd post (code=exited, status=0/SUCCESS)
  Process: 8736 ExecStart=/usr/bin/mysqld_safe (code=exited, status=1/FAILURE)
  Process: 8708 ExecStartPre=/usr/bin/mysql-systemd pre (code=exited, status=0/SUCCESS)  Main PID: 8736 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/mysqld.service

Sep 15 15:21:16 server.mydomain.com systemd[1]: Unit mysqld.service entered failed state.
Sep 15 15:21:16 server.mydomain.com systemd[1]: Triggering OnFailure= dependencies of mysqld.service.
Sep 15 15:21:16 server.mydomain.com systemd[1]: mysqld.service failed.`

Mysql works but it keeps restarting over and over again. I have tried rebooting the server and also killing the mysqld_safe but it keeps on restarting. 

Any suggestions?

**Comment by gladroger** [comment]
Seems very fishy why it does it but I managed to fix it for the moment by stopping the mysql server with `service mysql stop` and then check if anything was running with `ps -e | grep mysql` and killed it with `kill -9 (number)` and then started it again with `service mysql start`

**Comment by magenx** [comment]
this was already reported,
you need either kill mysqld_safe or reboot
