### ISSUE TITLE
MAGENTO DATABASE AND DATABASE USER

### ISSUE THREAD

**Issue by bahramdavodi** [magenx/Magento-Automated-Server-Configuration-from-MagenX#142]
Hello.
in the new version have a problem with create user and pass in db.

missing close-bracket
    while executing
"send "Lo^^KfG]IpN[tnk\r"
expect "Re-enter new password:"
send "Lo^^KfG]IpN[tnk\r"
expect "Remove anonymous users?"
send "y\r"
expect "Disallow root lo..."

---> Enter Magento database host : localhost
---> Enter Magento database name : m2d_7eb3_170917
---> Enter Magento database user : m2u_b510_170917

------> Press [Enter] key to create MySQL database and user
Warning: Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

thanks

**Comment by magenx** [comment]
it should work now ok

**Comment by GeboCermex** [comment]
I have the same problem, AM i doing something worng

**Comment by a00811418** [comment]
Same problem, how can I fix or what am I doing wrong? @magenx
