### ISSUE TITLE
Install error message `config` Job for proftpd.service failed because the control process exited with error code. See "systemctl status proftpd.service" and "journalctl -xe" for details.

### ISSUE THREAD

**Issue by agunes77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#143]
SERVER HOSTNAME SETTINGS

                SERVER TIMEZONE SETTINGS

                HHVM AND PHP-FPM SETTINGS

                NGINX SETTINGS

                PHPMYADMIN INSTALLATION AND CONFIGURATION

                PROFTPD CONFIGURATION

Job for proftpd.service failed because the control process exited with error code. See "systemctl status proftpd.service" and "journalctl -xe" for details.

                VARNISH CACHE SETTINGS
                VARNISH CACHE PORT :8081

                OPCACHE GUI, n98-MAGERUN, IMAGE OPTIMIZER, MYSQLTUNER, SSL DEBUG TOOLS

                SYSTEM AUTO UPDATE WITH YUM-CRON

                LETSENCRYPT SSL CERTIFICATE REQUEST

                DNS A record and your servers IP address do not match

**Comment by magenx** [comment]
could you please post error message here

**Comment by agunes77** [comment]
systemctl status proftpd.service
● proftpd.service - ProFTPD FTP Server
   Loaded: loaded (/etc/systemd/system/proftpd.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2017-09-22 18:51:27 +03; 1s ago
  Process: 14908 ExecStart=/usr/sbin/proftpd $PROFTPD_OPTIONS (code=exited, status=1/FAILURE)

Sep 22 18:51:27 server.agunesxtshop.com systemd[1]: Triggering OnFailure= dependencies of proftpd.service.
Sep 22 18:51:27 server.agunesxtshop.com systemd[1]: proftpd.service failed.

You have new mail in /var/spool/mail/root
eroor message:
From root@server.agunesxtshop.com  Fri Sep 22 17:15:41 2017
Return-Path: <root@server.agunesxtshop.com>
X-Original-To: root
Delivered-To: root@server.agunesxtshop.com
Received: by server.agunesxtshop.com (Postfix, from userid 0)
	id 2D8521E0308; Fri, 22 Sep 2017 17:15:41 +0300 (+03)
From: "(Cron Daemon)" <root@server.agunesxtshop.com>
To: root@server.agunesxtshop.com
Subject: Cron <root@server> run-parts /etc/cron.hourly
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=1642>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/0>
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/bash>
X-Cron-Env: <PATH=/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <MAILTO=root>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Message-Id: <20170922141541.2D8521E0308@server.agunesxtshop.com>
Date: Fri, 22 Sep 2017 17:15:41 +0300 (+03)

var/log/maillog
Sep 22 20:03:20 localhost postfix/pickup[24940]: DE074260419: uid=0 from=<root>
Sep 22 20:03:20 localhost postfix/cleanup[24829]: DE074260419: message-id=<20170922170320.DE074260419@server.agunesxtshop.com>
Sep 22 20:03:20 localhost postfix/qmgr[1871]: DE074260419: from=<root@server.agunesxtshop.com>, size=1081, nrcpt=1 (queue active)
Sep 22 20:03:20 localhost postfix/error[26187]: DE074260419: to=<admin@agunesxtshop.com>, relay=none, delay=0.01, delays=0/0/0/0, dsn=4.4.1, status=deferred (delivery temporarily suspended: connect to agunesxtshop.com[176.33.73.xxx]:25: Connection refused)
