### ISSUE TITLE
Script `CONFIG` screen error

### ISSUE THREAD

**Issue by agunes77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#144]
config
-------------------------------------------------------------------------------------
| POST-INSTALLATION CONFIGURATION |
-------------------------------------------------------------------------------------

                SERVER HOSTNAME SETTINGS

                SERVER TIMEZONE SETTINGS

                HHVM AND PHP-FPM SETTINGS

                NGINX SETTINGS

                PHPMYADMIN INSTALLATION AND CONFIGURATION
http://mirror.innosol.asia/remi/enterprise/7/remi/x86_64/composer-1.5.2-1.el7.remi.noarch.rpm: [Errno 12] Timeout on http://mirror.innosol.asia/remi/enterprise/7/remi/x86_64/composer-1.5.2-1.el7.remi.noarch.rpm: (28, 'Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds')
Trying other mirror.

                PROFTPD CONFIGURATION

Job for proftpd.service failed because the control process exited with error code. See "systemctl status proftpd.service" and "journalctl -xe" for details.

                VARNISH CACHE SETTINGS
                VARNISH CACHE PORT :8081

                OPCACHE GUI, n98-MAGERUN, IMAGE OPTIMIZER, MYSQLTUNER, SSL DEBUG TOOLS

                SYSTEM AUTO UPDATE WITH YUM-CRON

                LETSENCRYPT SSL CERTIFICATE REQUEST

                DNS A record and your servers IP address do not match
                Your servers ip address 192.168.1.9

**Comment by magenx** [comment]
first error is about your local yum mirrors, second is about proftpd config,
you can take a look `systemctl status proftpd.service` or `journalctl -xe` and fix it in `/etc/proftpd.conf`
