### ISSUE TITLE
/var/log/messages logs

### ISSUE THREAD

**Issue by agunes77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#145]
Nov  9 18:40:48 server systemd: proftpd.service failed.
Nov  9 18:40:48 server systemd: Started Service Status Monitor.
Nov  9 18:40:48 server systemd: Starting Service Status Monitor...
Nov  9 18:40:48 server journal: Suppressed 203 messages from /system.slice/postfix.service
Nov  9 18:40:56 server systemd: mysqld.service holdoff time over, scheduling restart.
Nov  9 18:40:56 server systemd: Starting MySQL Percona Server...
Nov  9 18:40:57 server mysqld_safe: 171109 18:40:57 mysqld_safe Adding '/usr/lib64/libjemalloc.so.1' to LD_PRELOAD for mysqld
Nov  9 18:40:57 server mysqld_safe: 171109 18:40:57 mysqld_safe Logging to '/var/lib/mysql/server.mysite.com.err'.
Nov  9 18:40:57 server mysqld_safe: 171109 18:40:57 mysqld_safe A mysqld process already exists
Nov  9 18:40:57 server systemd: mysqld.service: main process exited, code=exited, status=1/FAILURE
Nov  9 18:40:57 server systemd: Failed to start MySQL Percona Server.
Nov  9 18:40:57 server systemd: Unit mysqld.service entered failed state.
Nov  9 18:40:57 server systemd: Triggering OnFailure= dependencies of mysqld.service.
Nov  9 18:40:57 server systemd: mysqld.service failed.
Nov  9 18:40:57 server systemd: Started Service Status Monitor.
Nov  9 18:40:57 server systemd: Starting Service Status Monitor...
Nov  9 18:40:59 server systemd: proftpd.service holdoff time over, scheduling restart.
Nov  9 18:40:59 server systemd: Starting ProFTPD FTP Server...
Nov  9 18:40:59 server proftpd: 2017-11-09 18:40:59,090 server.mysite.com proftpd[23526]: warning: unable to determine IP address of 'server.mysite.com'
Nov  9 18:40:59 server proftpd: 2017-11-09 18:40:59,090 server.mysite.com proftpd[23526]: error: no valid servers configured
Nov  9 18:40:59 server proftpd: 2017-11-09 18:40:59,090 server.mysite.com proftpd[23526]: fatal: error processing configuration file '/etc/proftpd.conf'
Nov  9 18:40:59 server systemd: proftpd.service: control process exited, code=exited status=1
Nov  9 18:40:59 server systemd: Failed to start ProFTPD FTP Server.
Nov  9 18:40:59 server systemd: Unit proftpd.service entered failed state.
Nov  9 18:40:59 server systemd: Triggering OnFailure= dependencies of proftpd.service.

**Comment by magenx** [comment]
mysql systemd config file issue fixed now.
