### ISSUE TITLE
Setup magento Database 

### ISSUE THREAD

**Issue by GeboCermex** [magenx/Magento-Automated-Server-Configuration-from-MagenX#146]
I'm trying to create database and still have this message

mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

---> Enter Magento database host : localhost
---> Enter Magento database name : m2d_2055_171129
---> Enter Magento database user : m2u_b76c_171129

------> Press [Enter] key to create MySQL database and user
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

**Comment by magenx** [comment]
you installed 5.7?
running "database" only once?

**Comment by GeboCermex** [comment]
yes I selected 57 and got this error at 1st attemp

**Comment by GeboCermex** [comment]
just to be sure when running this command am I running the latest version of your script ? 

curl -o mascm.sh -L https://masc.magenx.com && sh mascm.sh

**Comment by magenx** [comment]
yes,but looks like password didnt work

**Comment by GeboCermex** [comment]
I retried with percona 56 and it worked fine so I'll stay with that for now thanks
