### ISSUE TITLE
404 conf files

### ISSUE THREAD

**Issue by pablfr** [magenx/Magento-Automated-Server-Configuration-from-MagenX#147]
Hello,

config file are in 404 : fastcgi_params, nginx.conf, default.conf and 

https://raw.githubusercontent.com/magenx/Magento-nginx-config/master/*

Thank

**Comment by magenx** [comment]
what is your error exactly?

**Comment by pablfr** [comment]
When I search for an understanding why the "ln" do not exist, I saw that the wget

![image](https://user-images.githubusercontent.com/1676195/33604102-14204018-d9b5-11e7-85a1-66428deeb014.png)
