### ISSUE TITLE
unable to access new php file in home....

### ISSUE THREAD

**Issue by GeboCermex** [magenx/Magento-Automated-Server-Configuration-from-MagenX#150]
Hi, I placed 2 new file sin the home folder of the magento site. I added the two file name inside the magento2.conf and restarted nginx. if I try to access them I have a file not found error.

I did a test I have a file previously added that is working using the same procedure. I modified the content of this php file and when I try to access it from a browser it show the old content not the new one.

I think it's because it's cached somewhere.. Is there a command I can do in ssh to clear all the caches ? I even disable all magento cache in the admin panel

**Comment by magenx** [comment]
files must be in `/pub/` folder.
opcache management file you can see in installation log 
`[opcache gui]: `

opcache will be reset automatically if you have DNS configured
