### ISSUE TITLE
After successful installation: How to make it run as fast as possible?

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#151]
I ran the installation without any problems yesterday.

I'm wondering what steps you take to make Magento 2 as fast as possible because your demo site is blazing fast.

**Comment by magenx** [comment]
manual changes are:
 - merge css/js + enable bundle
 - use cookie-less subdomain for static/media
 - enable varnish cache + nginx proxy
 - compile nginx with mod pagespeed
 - enable magento production mode

also your theme must be coded very good.

**Comment by gladroger** [comment]
Thank you for all suggestions!
