### ISSUE TITLE
Advanced Search /catalogsearch/advanced/ 502 Bad gateway

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#152]
I get error 502 Bad Gateway on the frontend at /catalog/search/advanced

From /var/log/nginx/error.log
2018/01/15 13:26:52 [error] 1542#1542: *2058 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.11.1, server: domain.com, request: "GET /catalogsearch/advanced/ HTTP/2.0", upstream: "fastcgi://127.0.0.1:9001", host: "domain.com", referrer: "https://domain.com/search/term/popular/"

**Comment by magenx** [comment]
config_m2/maps.conf 
remove 9001 port to hhvm

looks like hhvm not working properly with php 7+ code

**Comment by gladroger** [comment]
Great, thanks. Can confirm it working now after disabling hhvm in maps.conf
