### ISSUE TITLE
Clearing cache correctly after major change.

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#153]
Sorry for noob question. 

I changed the Magento mode from production back to developer mode.

I wanted the developer option in the admin advanced menu but could not see it after changing mode. 
So I flushed all caches I could think of to
 flush the Magento cache with 'bin/magento cache:clean' even though it was disabled.  
 clear redis with 'redis-cli flushall'
 clear varnish with 'service varnish restart'

Still, Developer did not show up in the stores - configuration - advanced, so I tried logging in and out. 

Try rebooting the server and developer suddenly appeared in the admin menu.

What cache am I missing to clear?

**Comment by magenx** [comment]
you can just create this file to clear all caches:

```
#!/bin/bash

redis-cli -p 6380 flushall
service php-fpm restart
service nginx restart
service varnish restart
```

**Comment by gladroger** [comment]
Great suggestion, thanks a lot!
