### ISSUE TITLE
Fresh install 502 Bad Gateway nginx (php-fpm issue)

### ISSUE THREAD

**Issue by BrM123** [magenx/Magento-Automated-Server-Configuration-from-MagenX#154]
/var/log/nginx/error.log

`2018/02/15 18:45:49 [error] 12111#12111: *101 connect() failed (111: Connection refused) while connecting to upstream, client: 78.31.224.29, server: timestorybag.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "timestorybag.com", referrer: "http://timestorybag.com/"`

[root@server ~]# systemctl status php-fpm.service
```
● php-fpm.service - The PHP FastCGI Process Manager
   Loaded: loaded (/etc/systemd/system/php-fpm.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-02-15 18:41:18 UTC; 7s ago
  Process: 31330 ExecStart=/usr/sbin/php-fpm --nodaemonize (code=exited, status=78)
 Main PID: 31330 (code=exited, status=78)
   CGroup: /system.slice/php-fpm.service

**Comment by magenx** [comment]
looks like some variable lost.
you can fix it by looking at every point where is error:
1 - `crontab -e`
2 - `/etc/php-fpm.d/www.conf`
3 - `/etc/yum/yum-cron.conf`
4 - `/usr/local/maldetect/conf.maldet`
5 - `/bin/service-status-mail.sh`

or try to install again.

**Comment by BrM123** [comment]
The problem is:

```
Feb 15 18:41:18 server.timestorybag.com systemd[1]: php-fpm.service: main process exited, code=exited, status=78/n/a
Feb 15 18:41:18 server.timestorybag.com systemd[1]: Failed to start The PHP FastCGI Process Manager.
Feb 15 18:41:18 server.timestorybag.com systemd[1]: Unit php-fpm.service entered failed state.
Feb 15 18:41:18 server.timestorybag.com systemd[1]: Triggering OnFailure= dependencies of php-fpm.service.
Feb 15 18:41:18 server.timestorybag.com systemd[1]: php-fpm.service failed.
```
I tried reinstalling several times, but the problem is the same. Problems with cron I do not see.
