### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by kauansoft** [magenx/Magento-Automated-Server-Configuration-from-MagenX#155]
Hello, can you make a tutorial?

Installation order priority is the same of shell listing?

I've install and I can not see Magento or webmin when I access through browser, I've released all ports and nothing, used command  `service nginx status `command and says it's running.

By now, im trying use hostname of own provider hosting, because with my own domain ins't working and give me an error:

` /usr/bin/certbot certonly --agree-tos --no-eff-email --email email@mydomain.com --webroot -w /home/admin/public_html/pub/ -d mydomain.com -d www.mydomain.com`

___________________________________________________

When i try install csf or f2b firewall its locks the process - Centos 7

Every help is welcome, thanks.

**Comment by magenx** [comment]
you must have DNS configured, or IP to domain pointer in your computer hosts file, to access domain.
also to configure certbot you need DNS configured.

please post any error.

**Comment by kauansoft** [comment]
I've setup again, and magento is working now! I did it with new update, but firewall got stucked again (maybe is fault of my provider hosting).

**Comment by bilgisay-center** [comment]
Hello,
how can i install and using this on my ubuntu server ?

Thank you.

**Comment by magenx** [comment]
only works in CentOS 7,
ubuntu has too many changes and faults in short time.
centos is more stable os.

**Comment by bilgisay-center** [comment]
ok i select to centos 7, how can i use this on that server? 


Thank you!

**Comment by magenx** [comment]
downoad and rut the script.

**Comment by bilgisay-center** [comment]
: ) great answer thank you!
other: how can i do that, has any userguide or video tutorial?


Thank you.
