### ISSUE TITLE
New installation several errors

### ISSUE THREAD

**Issue by JerTeske** [magenx/Magento-Automated-Server-Configuration-from-MagenX#157]
Hello, I'm brand new to magento and was running script and came into a few snags. This was my first time running this script on a brand new VPS on Cent OS 7.4. I have provided the error log that I received on the first run. I will be reformatting and starting again to see if there wasn't another error I missed somewhere.

I did notice that the PHP My Admin, is calling the old 7.0 version instead of 7.1

| POST-INSTALLATION CONFIGURATION |
-------------------------------------------------------------------------------------

                SERVER HOSTNAME SETTINGS

                SERVER TIMEZONE SETTINGS
Invalid number of arguments.

                PHP-FPM SETTINGS
sed: -e expression #1, char 51: unterminated `s' command

                NGINX SETTINGS
sed: can't read /etc/nginx/sites-available/magento2.conf: No such file or directory
sed: can't read /etc/nginx/sites-available/magento2.conf: No such file or directory
sed: can't read /etc/nginx/conf_m2/extra_protect.conf: No such file or directory

                PHPMYADMIN INSTALLATION AND CONFIGURATION
Could not retrieve mirrorlist http://cdn.remirepo.net/enterprise/7/**php70**/mirror error was
14: curl#6 - "Could not resolve host: cdn.remirepo.net"

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: remi-php70
sed: can't read /etc/phpMyAdmin/config.inc.php: No such file or directory
sed: can't read /etc/nginx/conf_m2/phpmyadmin.conf: No such file or directory
sed: can't read /etc/nginx/conf_m2/phpmyadmin.conf: No such file or directory

                PROFTPD CONFIGURATION

                VARNISH CACHE SETTINGS
                VARNISH CACHE PORT :8081

                OPCACHE GUI, n98-MAGERUN, IMAGE OPTIMIZER, MYSQLTUNER, SSL DEBUG TOOLS

                SYSTEM AUTO UPDATE WITH YUM-CRON
sed: -e expression #1, char 52: unterminated `s' command

                LETSENCRYPT SSL CERTIFICATE REQUEST

                DNS A record and your servers IP address do not match
                Your servers ip address 208.115.99.197
                Domain bizbloccenter.com resolves to
                Please change your DNS A record to this servers IP address, and run this command later:
                /usr/bin/certbot certonly --agree-tos --no-eff-email --email admin@bizbloccenter.com admin@bizbloccenter.com --webroot -w /home/Shopkeep/public_html/pub/ -d bizbloccenter.com -d www.bizbloccenter.com

                GENERATE DHPARAM FOR NGINX SSL
Generating DSA parameters, 4096 bit long prime
..+.+............+...........+...+......+................+...+..+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*
+......................................+..........+..........+..+..+...+...+..+.+.....................................+.+...................+..........+................+...+........+......+......+.......+.........+...........+...+.....+..................+...+...........+.......+....+........+.....................+............+........+.......+.+..+......+.+....................................+..........+.+...+..................+.....+......+...........+.....+................+...+.......+.+........................+...+.....................+..+.......+................+...+.+........+..........+.+..+.......................+...+.....+......+.......+...........+......+.+......+.+..+.+...+..........+....+...+..............+.....+..+.....+............+..+...........................+...+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*

                GENERATE DEFAULT NGINX SSL SERVER KEY/CERT
Generating a 4096 bit RSA private key
............................................................................................++
......................................++
writing new private key to '/etc/ssl/certs/default_server.key'
-----

                SIMPLE LOGROTATE SCRIPT FOR MAGENTO LOGS

                SERVICE STATUS WITH E-MAIL ALERTING
sed: -e expression #1, char 40: unterminated `s' command

                MAGENTO MALWARE SCANNER
                Hourly cronjob created
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2c61a90>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mwscan/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2c61290>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mwscan/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2c61190>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mwscan/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2c61350>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mwscan/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2c61150>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/mwscan/
  Could not find a version that satisfies the requirement mwscan (from versions: )
No matching distribution found for mwscan

                MALDET MALWARE MONITOR WITH E-MAIL ALERTING
                warning: infected files will be moved to quarantine
Cloning into 'linux-malware-detect'...
fatal: unable to access 'https://github.com/rfxn/linux-malware-detect.git/': Could not resolve host: github.com
magenx.sh: line 1326: cd: linux-malware-detect: No such file or directory
sed: can't read /usr/local/maldetect/conf.maldet: No such file or directory
sed: -e expression #1, char 40: unterminated `s' command
sed: can't read /usr/local/maldetect/conf.maldet: No such file or directory
sed: can't read /usr/local/maldetect/conf.maldet: No such file or directory
magenx.sh: line 1333: /usr/local/maldetect/monitor_paths: No such file or directory
cp: cannot stat ‘/usr/lib/systemd/system/maldet.service’: No such file or directory
sed: can't read /etc/systemd/system/maldet.service: No such file or directory
sed: can't read /etc/systemd/system/maldet.service: No such file or directory

                GOACCESS REALTIME ACCESS LOG DASHBOARD
Cloning into 'goaccess'...
fatal: unable to access 'https://github.com/allinurl/goaccess.git/': Could not resolve host: github.com
magenx.sh: line 1347: cd: goaccess: No such file or directory
autoreconf: 'configure.ac' or 'configure.in' is required

                MAGENTO CRONJOBS
"rootcron":3: bad minute
errors in crontab file, can't install.

                REDIS CACHE AND SESSION STORAGE

Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
Job for php-fpm.service failed because the control process exited with error code. See "systemctl status php-fpm.service" and "journalctl -xe" for details.
                OPCACHE INVALIDATION MONITOR

                DISABLE MAGENTO CACHE AND ENABLE DEVELOPER MODE
Enabled developer mode.
Flushed cache types:
config
layout
block_html
collections
reflection
db_ddl
eav
customer_notification
config_integration
config_integration_api
full_page
translate
config_webservice
Changed cache status:
                        config: 1 -> 0
                        layout: 1 -> 0
                    block_html: 1 -> 0
                   collections: 1 -> 0
                    reflection: 1 -> 0
                        db_ddl: 1 -> 0
                           eav: 1 -> 0
         customer_notification: 1 -> 0
            config_integration: 1 -> 0
        config_integration_api: 1 -> 0
                     full_page: 1 -> 0
                     translate: 1 -> 0
             config_webservice: 1 -> 0
sed: can't read /etc/nginx/sites-available/magento2.conf: No such file or directory
Job for php-fpm.service failed because the control process exited with error code. See "systemctl status php-fpm.service" and "journalctl -xe" for details.

**Comment by magenx** [comment]
thank you for you report
we need to add few more checks to stop script if there is any networking issues,
and if some files or variables can not be downloaded or set.

**Comment by JerTeske** [comment]
GREENTXT "SERVER HOSTNAME SETTINGS"
hostnamectl set-hostname server.${MAGE_DOMAIN} --static

This line is causing resolv.conf to be rewritten by Network Manager, causing OS to use DNS and stopping further downloads from GitHub. 

Current solution to this is sudo chattr +I /etc/resolv.conf to stop getting overwritten or systemctl stop NetworkManager
