### ISSUE TITLE
MY_DOMAIN

### ISSUE THREAD

**Issue by btray77** [magenx/Magento-Automated-Server-Configuration-from-MagenX#24]
If you have to leave the script for some reason it forgets MY_DOMAIN which causes issues with the install portion of the script.  
MY_DOMAIN is never read from /root/mascm/.mascm_index

**Comment by magenx** [comment]
which file? for centos 6 or 7?

**Comment by btray77** [comment]
centos 7

**Comment by magenx** [comment]
yes, this variable name is mixed MY_DOMAIN -> DOMAIN. probably will be fixed :+1:
