### ISSUE TITLE
Error regarding Centos 7 and Magento 1.9.2.3 with PHP my admin

### ISSUE THREAD

**Issue by igc-ruud** [magenx/Magento-Automated-Server-Configuration-from-MagenX#25]
Hi,

After installing the configuration I have the following error in PhpMyAdmin:

Warning in ./libraries/session.inc.php#101
 session_start(): open(/var/lib/php/session/sess_nrouv2ucocjjjipr7epqmppepjmn3fav, O_RDWR) failed: Permission denied (13)

Backtrace

./libraries/session.inc.php#101: session_start()
./libraries/common.inc.php#350: require(./libraries/session.inc.php)
./index.php#12: require_once(./libraries/common.inc.php)

Did you experience this error before?

I would be happy to hear from you.

Kind regards,

Ruud

**Comment by magenx** [comment]
yes, this path `/var/lib/php/session` is not writable.
it must be owned by php user. after installation php creates this folder as `root:apache`
