### ISSUE TITLE
chown issue

### ISSUE THREAD

**Issue by ysm1mh** [magenx/Magento-Automated-Server-Configuration-from-MagenX#26]
`chown -R ${MY_DOMAIN%%.*}:${MY_DOMAIN%%.*} ${MY_SHOP_PATH%/*}`  on line 737 giving a problem.

when fix permissions is running centos gives a error with   :  error after this permissions arent set and i am stuck here.

**Comment by magenx** [comment]
what error??

**Comment by ysm1mh** [comment]
---> FIXING PERMISSIONS
chown: missing operand after ‘:’
Try 'chown --help' for more information.

**Comment by magenx** [comment]
there is something wrong, missing domain name

**Comment by webdaDev** [comment]
got the same error here.

> there is something wrong, missing domain name

is this Script able to install on a Subdomain?
