### ISSUE TITLE
Getting Error: NETWORK IS DOWN? on AWS

### ISSUE THREAD

**Issue by ewebhub** [magenx/Magento-Automated-Server-Configuration-from-MagenX#27]
I had install MagenX git on aws MagenX m4.large and when try to run the Magnex Configuration getting error mesage as 
>  ERROR: NETWORK IS DOWN?
                ------> PLEASE CHECK YOUR NETWORK SETTINGS.

I am able to update and install any other application, but not able to run the Magnex Configuration due to the ERROR: NETWORK IS DOWN?
![magenx error 2016-03-11_11-28-31](https://cloud.githubusercontent.com/assets/13046674/13694678/bf363196-e77d-11e5-8d83-3a8ea4a57d9f.jpg)

Please advice how to fix it.

Thanks in advance

**Comment by magenx** [comment]
what you see if you paste this and run in console: <br/>
`(ping -w3 -c2 74.125.24.106 || ping -w3 -c2 208.80.154.225) && echo "up" || (echo "down" && exit 1)`

**Comment by ewebhub** [comment]
4 packets transmitted, 0 received, 100% packet loss, time 2999ms

PING 208.80.154.225 (208.80.154.225) 56(84) bytes of data.

--- 208.80.154.225 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 2999ms

**Comment by magenx** [comment]
you have something wrong with your network or firewall, these two ip addresses from google and wikipedia

**Comment by ewebhub** [comment]
yes i agree, but i am able to update the instance, install the git and git magnx clone have no issues, only when trying to run the Magnex Configuration, getting the error message, 

its a freshly lunched instance with only git magenx clone installed, Nothing else. 

I will see what's wrong form my end

Thanks for you help

**Comment by ewebhub** [comment]
Problem solver, Need to make Changes in AWS Security Group Outbound
>ALL Traffic Protocol Port Range Destination as Anywhere
