### ISSUE TITLE
Blank Page after the Installation for Magneto 1.9 on centos-7

### ISSUE THREAD

**Issue by ewebhub** [magenx/Magento-Automated-Server-Configuration-from-MagenX#28]
I had run the MagenX git on AWS m4.large and had complete all steps of installation. 
After the installation I am not able to access the Front and Backend (admin login), Getting Blank Page.

I had deleted all the files from the cache through vsftpd setup as proftpd by magenx installation not working on AWS and also try uncomment (by removing leading hash character) the following code: `ini_set('display_errors', 1);`

Still getting the same blank Page Front and Backend (admin login)

During the installation I notice you had update the Magento/CentOS-7/MASC-M-7.sh to PHP 7 and Varnish 4.

Does the current magenx magento 1.9.2.4 support the PHP 7 and Varnish 4 latest Version.

I had see the magento-turpentine git for issues running Varnish 4 latest Version on centos & check out post [https://github.com/nexcess/magento-turpentine/issues/1086](url)

is the current magento 1.9.2.4 patched with any compatibility extension to work with PHP 7.

Please Help me how fix this Blank Page issue

Thanks in advance

**Comment by mrlerch** [comment]
Try installing this: https://github.com/Inchoo/Inchoo_PHP7

**Comment by mrlerch** [comment]
But if you are planning on using AvaTax extension then you have to downgrade your PHP to PHP 5.5.33. One Pica responded that they will make their extension compatible with PHP 7 when Magento officially supports it.

**Comment by magenx** [comment]
http://magento.stackexchange.com/questions/74008/is-magento-ready-for-php-7
