### ISSUE TITLE
system doesn't work for me at all after setup...

### ISSUE THREAD

**Issue by CKUDG** [magenx/Magento-Automated-Server-Configuration-from-MagenX#29]
only webmin was accessible...

do you have any more detailed documentation on how the complete setup works?

Maybe i did something wrong..?

I did the following:

1. set up an cents 7.2 droplet on digital ocean
2. installed git
3. cloned the repo
4. executed the MASC-M-7-v2.sh
5. did all steps from the menu after each other... entered all the needed configurations etc.
6. finally only the webmin panel was reachable for me... 

The shop frontend as also backend wasn't reachable, also the phpmyadmin wasn't reachable nor the opcache...

Thanks much for any more detailed "how to setup" documentations

best regards,
Christian

**Comment by magenx** [comment]
you need to look into nginx, php and magento error logs
