### ISSUE TITLE
Cannot load Zend OPcache - it was already loaded

### ISSUE THREAD

**Issue by BluePearlXT** [magenx/Magento-Automated-Server-Configuration-from-MagenX#30]
[root@localhost ~]# php -v
Cannot load Zend OPcache - it was already loaded
PHP 7.0.4 (cli) (built: Mar  2 2016 18:03:26) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by BluePearlXT** [comment]
Magento is not installed
500 server gives an error

**Comment by magenx** [comment]
is there any other errors you have in the logs?

**Comment by magenx** [comment]
right, we use php 7 latest as defoult now,
so for magento 1.9 to work with php 7 you need to do some changes to make it fly:
http://magento.stackexchange.com/questions/74008/is-magento-ready-for-php-7


thank you

**Comment by magenx** [comment]
fixed
