### ISSUE TITLE
Issues showing up wordpress recent posts

### ISSUE THREAD

**Issue by rvasarvindh** [magenx/Magento-Automated-Server-Configuration-from-MagenX#31]
Hi,

First of all thanks for an excellent automated script. We are using Centos 7, Nginx with PHP 5.6. We have integrated worpdress with Magento. We are having issues with showing recent posts . http://staging.mjtestsrv.net/laromedel  in this page "Läs vår blogg! "  (block) in left bottom have to show wordpress recent posts which is using the code 

Query.getJSON("<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>wordpress/wp-json.php/posts")
        .done(function (data) {
           var htmlString = "";

            jQuery.each(data, function (index, entry) {

                htmlString += "<a href =\"" + entry.link + "\">";

                htmlString += "<h4>" + entry.title + "</h4>";

                htmlString += "<p>" + entry.content.substr(0, 100) + "...</p>";

                htmlString += "</a>";

            });

            jQuery(".blogg-wrapper").append(htmlString);

        })

        .fail(function (jqxhr, textStatus, error) {

            var err = textStatus + ", " + error;

            console.log("Request Failed: " + err);

        });

But the same is working if we use apache. Do we need to add anything to nginx configuration.

**Comment by magenx** [comment]
this link return 404:
`http://staging.mjtestsrv.net/wordpress/wp-json.php/posts`

**Comment by rvasarvindh** [comment]
As you see this site is hosted under 

http://staging.mjtestsrv.net/wordpress/

Can you suggest me the NGINX configuration to make it work?

**Comment by magenx** [comment]
you need to check your rewrites for wordpress/ subfolder and php path configuration.
really hard to say remotely.

**Comment by rvasarvindh** [comment]
Here is my nginx conf

##   Add www
#server {
#   include /etc/nginx/port.conf;
#    server_name staging.mjtestsrv.net;
 #   return 301 $scheme://www.staging.mjtestsrv.net$request_uri;
#}

server {   
    include /etc/nginx/port.conf;
    #listen 443 http2 ssl;
    server_name staging.mjtestsrv.net;
    root /var/www/html/main;
    access_log  /var/log/nginx/access_www.staging.mjtestsrv.net.log  main if=$writelog;
    error_log	/var/log/nginx/error_www.staging.mjtestsrv.net.log  error;
    
    if ($bad_client) { return 444; }
    
    ## Pagespeed module
       #include /etc/nginx/conf.d/pagespeed.conf;

    ## SSL CONFIGURATION
       #ssl_certificate     /etc/ssl/certs/server.crt; 
       #ssl_certificate_key /etc/ssl/certs/server.key;
    
    location = /js/index.php/x.js {
       rewrite ^(.*\.php)/ $1 last;
       }

    ## Main Magento @location
    location / {
       try_files $uri $uri/ @rewrite;
       }
    ## Server maintenance block.
       #include /etc/nginx/conf.d/maintenance.conf;
    ## Error log/page
       #include /etc/nginx/conf.d/error_page.conf;

    ## Export folder
       include /etc/nginx/conf.d/export.conf;
       
    ## These locations are protected
    location ~ /(app|var|downloader|includes|pkginfo)/ {
       deny all;
       }
        
    ## Extra protection and limits
       include /etc/nginx/conf.d/extra_protect.conf;
    
    ## Images
    location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
       expires max;
       log_not_found off;
       access_log off;
       add_header ETag "";
       }
	
location /wordpress {
try_files $uri $uri/ /wordpress/index.php?q=$uri&$args;
} 

   location @rewrite {
       rewrite / /index.php?$args;
       }
     	
    ## Execute PHP scripts
    location ~ \.php$ {
       include /etc/nginx/conf.d/headers.conf;
       try_files $uri =404;
       fastcgi_pass 127.0.0.1:9000;
       #fastcgi_pass 127.0.0.1:$port_switch;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_split_path_info ^(.+\.php)(/.+)$;
       ## Store code with multi domain
       #fastcgi_param MAGE_RUN_CODE $mage_code;
       #fastcgi_param MAGE_RUN_TYPE $mage_type;
       include fastcgi_params;
       }

    }

**Comment by magenx** [comment]
could you please send us access to the server so i can check it. `admin@magenx.com`

**Comment by magenx** [comment]
please take a look at your nginx config now, you can manipulate with wordpress separate block, also with cgi fix pathinfo  to get desired results.

**Comment by rvasarvindh** [comment]
Thanks a lot :) . Any update on Redis, Varnish not auto running after deployment 

 
Arvindh Srinivasan |  +91 98841 72076 | arvindh@outlook.com
Please consider the environment before printing this e-mail!IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

Date: Mon, 21 Mar 2016 01:47:38 -0700

**Comment by magenx** [comment]
redis must work after installation, you have them running?
```
redis      763  0.0  0.1 142760  5772 ?        Ssl  Mar20   0:41 /usr/bin/redis-server 127.0.0.1:6380
redis      788  0.0  0.1 142760  5748 ?        Ssl  Mar20   0:41 /usr/bin/redis-server 127.0.0.1:6379
```
but for varnish you need to manually swap ports with nginx if you are going to use it with turpentine.

**Comment by rvasarvindh** [comment]
OK. thanks a lot will do the same. Once again your suppport is appreciated.
 
Arvindh Srinivasan |  +91 98841 72076 | arvindh@outlook.com
Please consider the environment before printing this e-mail!IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

Date: Mon, 21 Mar 2016 01:56:50 -0700

**Comment by rvasarvindh** [comment]
Hi,

I didnt get HHVM, Redis to work with this Server. Can you help me to make it work?

When I try to test HHVM getting the following reply

Failed to restart redis.service: Unit redis.service failed to load: No such file or directory.
[root@staging hhvm]# hhvm -m server
[Mon Mar 21 15:15:42 2016] [hphp] [5333:7fca5a1bb3c0:0:000001] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:43 2016] [hphp] [5333:7fca5a1bb3c0:0:000002] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:44 2016] [hphp] [5333:7fca5a1bb3c0:0:000003] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:45 2016] [hphp] [5333:7fca5a1bb3c0:0:000004] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:46 2016] [hphp] [5333:7fca5a1bb3c0:0:000005] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:47 2016] [hphp] [5333:7fca5a1bb3c0:0:000006] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:48 2016] [hphp] [5333:7fca5a1bb3c0:0:000007] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:49 2016] [hphp] [5333:7fca5a1bb3c0:0:000008] [] 98failed to bind to async server socket: [::]:80: Address already in use

[root@staging hhvm]# service redis start
Redirecting to /bin/systemctl start  redis.service
Failed to start redis.service: Unit redis.service failed to load: No such file or directory.

 
Arvindh Srinivasan |  +91 98841 72076 | arvindh@outlook.com
Please consider the environment before printing this e-mail!IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

Date: Mon, 21 Mar 2016 01:56:50 -0700

**Comment by rvasarvindh** [comment]
Hi,

Im trying to enable SSL & Try to make HHVM up & running. Again the recent posts not appearing in the following pages

https://staging.mjtestsrv.net/laromedel

We are going live on monday with a different URL so I have loaded that SSL certificate in it.

Kindly let me know what needs to be changed in config for getting SSL, HHVM to get work . I wont disturb you further. If you need server details then

staging.mjtestsrv.net
root
r00tL0gme!n16

Thanks & Regards,
 
Arvindh Srinivasan |  +91 98841 72076 | arvindh@outlook.com
Please consider the environment before printing this e-mail!IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

From: arvindh@outlook.com
To: reply@reply.github.com; magento-automated-server-configuration-from-magenx@noreply.github.com
Subject: RE: [Magento-Automated-Server-Configuration-from-MagenX] Issues showing up wordpress recent posts (#31)
Date: Mon, 21 Mar 2016 20:47:06 +0530




Hi,

I didnt get HHVM, Redis to work with this Server. Can you help me to make it work?

When I try to test HHVM getting the following reply

Failed to restart redis.service: Unit redis.service failed to load: No such file or directory.
[root@staging hhvm]# hhvm -m server
[Mon Mar 21 15:15:42 2016] [hphp] [5333:7fca5a1bb3c0:0:000001] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:43 2016] [hphp] [5333:7fca5a1bb3c0:0:000002] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:44 2016] [hphp] [5333:7fca5a1bb3c0:0:000003] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:45 2016] [hphp] [5333:7fca5a1bb3c0:0:000004] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:46 2016] [hphp] [5333:7fca5a1bb3c0:0:000005] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:47 2016] [hphp] [5333:7fca5a1bb3c0:0:000006] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:48 2016] [hphp] [5333:7fca5a1bb3c0:0:000007] [] 98failed to bind to async server socket: [::]:80: Address already in use
[Mon Mar 21 15:15:49 2016] [hphp] [5333:7fca5a1bb3c0:0:000008] [] 98failed to bind to async server socket: [::]:80: Address already in use

[root@staging hhvm]# service redis start
Redirecting to /bin/systemctl start  redis.service
Failed to start redis.service: Unit redis.service failed to load: No such file or directory.

 
Arvindh Srinivasan |  +91 98841 72076 | arvindh@outlook.com
Please consider the environment before printing this e-mail!IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

Date: Mon, 21 Mar 2016 01:56:50 -0700

**Comment by magenx** [comment]
everything is working after installation, you just need to change ports for varnish, hhvm and nginx, all configuration files already in place.
