### ISSUE TITLE
Ubuntu 14.04?

### ISSUE THREAD

**Issue by nntoan** [magenx/Magento-Automated-Server-Configuration-from-MagenX#32]
Hello,
Is there any chance to make it work with Ubuntu series?

**Comment by magenx** [comment]
do not use ubuntu, really... use centos 7

**Comment by igc-ruud** [comment]
I don't understand what is against Ubuntu? Is it performance, security or what?

In my opinion the repository management of Ubuntu is way better than with CentOS

**Comment by magenx** [comment]
while rh/centos 7 has everything, this is about system administration and your daily tasks. centos is more user friendly server os than anything else. more compatibility and security. ubuntu is too fragile, unfortunately it breaks too often just in the middle...
