### ISSUE TITLE
AWS Linux OS?

### ISSUE THREAD

**Issue by webdaDev** [magenx/Magento-Automated-Server-Configuration-from-MagenX#33]
Is this working on Amazon AWS Linux?

**Comment by magenx** [comment]
install CentOS 7 image, do not use any derivatives...

**Comment by webdaDev** [comment]
Do you know if there are any CentOS 7 images on AWS community for t2.micro?

**Comment by magenx** [comment]
https://aws.amazon.com/marketplace/pp/B00O7WM7QW
