### ISSUE TITLE
Transfer existing Magento site

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-Automated-Server-Configuration-from-MagenX#36]
Hi, thank you for your work!

1. How I can correct migrate existing magento store from other server to your automated generated server?
2. How can can enable http2 and mgx_pagespeed modules?

**Comment by magenx** [comment]
install everything then remove magento only files, and rsync your old shop files.

**Comment by skazhikadyadya** [comment]
Thanks,

but how i can transfer to my old site all auto-configured magento settings?

**Comment by skazhikadyadya** [comment]
Oops, i solve my problem, thank you.
