### ISSUE TITLE
Incoming Mails

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-Automated-Server-Configuration-from-MagenX#37]
Hello, I have some emails like:

```
PHP Fatal error:  Uncaught Error: Class 'Mage_Aoe_Scheduler_Helper_Compatibility' not found in /var/www/html/domain.com/app/Mage.php:547
Stack trace:
#0 /var/www/html/domain.com/shell/scheduler.php(15): Mage::helper('aoe_scheduler/c...')
#1 /var/www/html/domain.com/shell/scheduler.php(436): Aoe_Scheduler_Shell_Scheduler->run()
#2 {main}
  thrown in /var/www/html/domain.com/app/Mage.php on line 547
```

Default installation on fresh CentOS 7/64. How I can fix that spam? Thanks.

**Comment by skazhikadyadya** [comment]
When i try to install Aoe_scheduler using mage i see that:

`install: Package community/Aoe_Scheduler 1.3.0: requires PHP version  >= 5.3.0 and <= 6.0.0  current is: 7.0.7`

**Comment by magenx** [comment]
probably you need to downgrade to php 5.6

**Comment by skazhikadyadya** [comment]
Can I simply remove

```
* * * * * ! test -e /var/www/html/royaltoys.ml/maintenance.flag && /bin/bash /var/www/html/domain.com/scheduler_cron.sh --mode always
* * * * * ! test -e /var/www/html/royaltoys.ml/maintenance.flag && /bin/bash /var/www/html/domain.com/scheduler_cron.sh --mode default
*/5 * * * * /bin/bash /var/www/html/domain.com/cron_check.sh
```

from my crontab? That's not fatal?

**Comment by igc-ruud** [comment]
I think the answer to your question is not to be answered here. Ofcourse you can remove items from your crontab, which means that the removed functionality will not work anymore. If this action is fatal is not up to this community to be answered, as nobody wants to be responsible for any failures.
