### ISSUE TITLE
centos6

### ISSUE THREAD

**Issue by rockdrigo** [magenx/Magento-Automated-Server-Configuration-from-MagenX#38]
why delete the centos6 configuraion files???

**Comment by magenx** [comment]
there is no point to keep it, `CentOS 6` has many drawbacks and limitations, while **CentOS 7** has everything up to date.

**Comment by rockdrigo** [comment]
@magenx yes, but still working, and It may be helpful to the community

**Comment by magenx** [comment]
yes, centos 5 still working too, but if you are going to install new server you have to use centos 7.
