### ISSUE TITLE
Magento 2 && Ansible

### ISSUE THREAD

**Issue by igc-ruud** [magenx/Magento-Automated-Server-Configuration-from-MagenX#39]
Hi,

First of all thanks for all the work you are doing. I really love your installs!

I have 2 questions for you:
1. I noticed that you removed the magento2 installation. Was there a specific reason for this and if not will this come back online.
2. I have worked a lot with ansible and I am wondering if you will be interested to work together on an ansible configuration for this script.

Please let me know.

Greets

**Comment by magenx** [comment]
1 - we have a contract with another company, and they asked us to move script to their private github repo. and work there only to upgrade it and modify. there are lots of forks anyway.

2 - just have no time for this.

**Comment by igc-ruud** [comment]
1. Ok to bad... I liked it that you shared it with us, but anyway thanks for the start.
2. There is another option, when I create this, can I use your settings and will you be able to have the overview.
