### ISSUE TITLE
session handler error

### ISSUE THREAD

**Issue by danipolo** [magenx/Magento-Automated-Server-Configuration-from-MagenX#40]
Script not working :(

When try to install just today I get this when login:

error magento/Framework/App/ErrorHandler->handler(2,'SessionHandler:...'

I've readed this on magento community: http://devdocs.magento.com/guides/v2.0/install-gde/trouble/php/tshoot_session.html

Need to downgrade magento version? Actually instaling: **2.1.0-rc3**

**Comment by magenx** [comment]
make sure your sessions folder is writeable

**Comment by danipolo** [comment]
I just run your script, it's a clean CentOS installation.
