### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by uinique-ruud** [magenx/Magento-Automated-Server-Configuration-from-MagenX#43]
On 2 servers we have the following issue:

<img width="1071" alt="1468238300" src="https://cloud.githubusercontent.com/assets/20240863/16729941/2558128a-4770-11e6-8b6f-04437d98ac27.png">

One of the servers is a magento 1 and the other a magento 2. Any idea where this comes from?

**Comment by magenx** [comment]
you need to check server logs, either nginx is not running or networking issue

**Comment by uinique-ruud** [comment]
Nginx is running correctly...
Strange thing is, this only happens with certain users.

**Comment by magenx** [comment]
then you need to find out which users, and then you can debug it
for me to understand it i have to see whats inside, logs .etc

**Comment by uinique-ruud** [comment]
I have more information about this error.

The admin does not work if 2 computers login over the same network. Than you get the error

**Comment by southerncomputer** [comment]
This is due to timeout not being configured on Varnish/Nginx/php-fpm for such a lengthy operation of deadlock against mysql!

I was hoping you(magenx) would complete this setup with HAPROXY(SSL)->Varnish->Nginx setup since most folks want to terminate with SSL

**Comment by bnmbr** [comment]
We had the same issue and found the problem, please see our answer on serverfault:

http://serverfault.com/questions/752203/apache-timeouts-when-2-users-with-same-ip

**Comment by magenx** [comment]
good to know.
will see what options needs to change but keep better defaults,

**Comment by uinique-ruud** [comment]
@bnmbr so if I understand this correct, you edited this value to 0?
net.ipv4.tcp_tw_recycle = 1

**Comment by uinique-ruud** [comment]
And what about:
net.ipv4.tcp_tw_reuse = 1
