### ISSUE TITLE
PhpMyAdmin cannot be installed with V2

### ISSUE THREAD

**Issue by tempo-ruud** [magenx/Magento-Automated-Server-Configuration-from-MagenX#45]
Installing phpMyAdmin - advanced MySQL interface
------> Press [Enter] key to continue

http://yum.gleez.com/7//repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

**Comment by magenx** [comment]
this is fixed now. some variables needs to be escaped properly. as you can see value is missing `/7/x86_64/repodata`
thank you for your help and bug reporting
