### ISSUE TITLE
Webmin Installation error v2

### ISSUE THREAD

**Issue by tempo-ruud** [magenx/Magento-Automated-Server-Configuration-from-MagenX#46]
---> Start the Webmin Control Panel installation? [y/n][n]:y

		Installation of Webmin package:

     PROCESSING  ###

		WEBMIN INSTALLATION ERROR

**Comment by magenx** [comment]
this is fixed now. some variables needs to be escaped properly.
thank you for your help and bug reporting

**Comment by tempo-ruud** [comment]
I had the same issue with HHVM, but forgot to copy that one.

**Comment by tempo-ruud** [comment]
And thanks for quick solving
