### ISSUE TITLE
Picking a timezone

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#47]
What format is the timezone question? Have tried using CEST or CET for Central Europe but it doesn't work and it doesn't error until it's fixing permissions and the installation fails.

**Comment by magenx** [comment]
language currency and timezone selection now working

**Comment by gladroger** [comment]
Testing again from a clean Centos install

Language, Currency and Timezone settings
./MASC-M-7-v2.sh: line 1220: bin/magento: Permission denied
---> Use up/down arrow keys then press enter to select MAGE_LOCALE
./MASC-M-7-v2.sh: line 134: item: bad array subscript
                                 ./MASC-M-7-v2.sh: line 136: item: bad array subscript

**Comment by magenx** [comment]
im sorry 
my mistake, forgot to chmod the file before
this is fixed now.

**Comment by gladroger** [comment]
Can confirm it's working awesomely now. Ran the script again from beginning and no errors. 

Thank you so much
