### ISSUE TITLE
How to set the Rest API on Magento 2

### ISSUE THREAD

**Issue by tempo-ruud** [magenx/Magento-Automated-Server-Configuration-from-MagenX#48]
Hi,

A quick question, can anyone help me how I can allow the REST api on magento 2:

Failed to load resource: the server responded with a status of 400 (Bad Request)
rest/default/V1/guest-carts/3d4a6115979518bdb1524b102006498a/set-payment-information

**Comment by magenx** [comment]
just tested `/swagger/`  all works ok

have you tested simple like this : `/rest/default/V1/directory/currency`

**Comment by tempo-ruud** [comment]
Yes that one is working, but the one I mentioned not.

**Comment by magenx** [comment]
could you please post any log messages for this request, maybe error, etc

**Comment by tempo-ruud** [comment]
I figured it out, it was an issue regarding php 7
