### ISSUE TITLE
 No port.conf and conf_m1 directory is empty

### ISSUE THREAD

**Issue by skazhikadyadya** [magenx/Magento-Automated-Server-Configuration-from-MagenX#49]
Hi, when i install all parts of MASC script nginx can't start: 

no port.conf file.
no /etc/nginx/conf_m1/spider.conf
...etc.

Where I can download sample conf files?

Thank you.

**Comment by magenx** [comment]
`https://github.com/magenx/Magento-nginx-config/tree/master/magento`

you say all configs downloaded but only `conf_m1` folder just empty?

**Comment by skazhikadyadya** [comment]
Thank you for link.

1. conf_m1 folder is empty.
2. port.conf file wasn't created.

**Comment by skazhikadyadya** [comment]
Hm, looks like *.conf files istead of conf_m1 folder written to sites-avaiable folder.

**Comment by magenx** [comment]
ah yes i see it now.
fixed
mkdir -p /etc/nginx/conf_m1 `&&` cd /etc/nginx/conf_m1/
thank you
