### ISSUE TITLE
Fixing Permissions 

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#50]
Getting a error at the end of the script, fixing permissions. 

---> FIXING PERMISSIONS
sed: -e expression #1, char 44: unknown option to `s'

                NOW CHECK EVERYTHING AND LOGIN TO YOUR BACKEND

---> Press [Enter] key to show menu

**Comment by magenx** [comment]
fixed

you can change your php timezone in php.ini
`date.timezone =`
