### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by corpsysgit** [magenx/Magento-Automated-Server-Configuration-from-MagenX#51]
404 Not Found after installation.

Link: http://www.teste.lojajstore.com

Thanks!

**Comment by magenx** [comment]
need more information: you can send us ssh access to check what went wrong there.
admin@magenx.com

**Comment by corpsysgit** [comment]
Thanks! 

I sent.

**Comment by corpsysgit** [comment]
Saw what worked and showed the installation page.
But I can not install magento or the ssh and not by the browser.
