### ISSUE TITLE
Wrong permissions, magento 1.9 version / centos7

### ISSUE THREAD

**Issue by Razko90** [magenx/Magento-Automated-Server-Configuration-from-MagenX#52]
Running the script on a fresh centos7 box. After the "install" command i get the error below. 

`chown: missing operand after 'user:user'
Try 'chown --help' for more information.
NOW LOGIN TO YOUR BACKEND AND CHECK EVERYTHING
---> Press [Enter] key to show menu
`

When i try to access the site:
every file (that should be) in the root folder /public_html/ is accessible 
for example: favicon.ico -> status 200

But every file thats in a subdir give me 403 permission denied: 

<img width="1680" alt="screen shot 2016-08-15 at 22 42 36" src="https://cloud.githubusercontent.com/assets/6859929/17678959/a3499224-6339-11e6-8193-dd75a75eb634.png">

**Comment by Razko90** [comment]
`Line 1227: chown -R ${MY_DOMAIN%%.*}:${MY_DOMAIN%%.*} ${MY_SHOP_PATH/*}`
`Line 1227: chown -R ${MY_DOMAIN%%.*}:${MY_DOMAIN%%.*} ${MY_SHOP_PATH%/*}`

Fixed the error message, but i still get 403 on the files even after i ran
`chown -R user:user /home/user`

**Comment by Razko90** [comment]
So after a little digging its something with the group permissions on the 
`setfacl -Rdm u:${MY_DOMAIN%%.*}:rwx,g:${MY_DOMAIN%%.*}:rw,g::rw,o::- ${MY_SHOP_PATH}`
line. 

If i run nginx as the same user as the directory its running fine. I thing group needs the X

**Comment by Razko90** [comment]
Yeah thanks for the awesome job you guys are doing! 
Doing this open sources saves so much time!

As a temporary work around, edit /etc/nginx/nginx.conf and change the first line to
user YOURUSERNAME;

And thanks again! 👍

**Comment by magenx** [comment]
yes, but another way to run `setfacl` with proper option.

**Comment by Razko90** [comment]
After running:

`[root@static public_html]# setfacl -Rdm g:USERNAME:rwx /home/USERNAME/public_html/
[root@static public_html]# getfacl /home/USERNAME/public_html/
getfacl: Removing leading '/' from absolute path names
# file: home/USERNAME/public_html/
# owner: USERNAME
# group: USERNAME
# flags: -s-
user::rwx
group::rwx
group:USERNAME:rwx
mask::rwx
other::---
default:user::rwx
default:user:USERNAME:rwx
default:group::rw-
default:group:USERNAME:rwx
default:mask::rwx
default:other::---
`

Its working as expected, thanks again this can be closed!
