### ISSUE TITLE
Post-install configuration

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#53]
POST-INSTALL CONFIGURATION
-------------------------------------------------------------------------------------
REDIS CACHE AND SESSION STORAGE

sed: can't read /home/user/public_htmlapp/etc/env.php: No such file or directory
sed: can't read /home/user/public_htmlapp/etc/env.php: No such file or directory

**Comment by magenx** [comment]
thank you , 
forward slash was missing.
fixed now
