### ISSUE TITLE
hhvm.service entered failed state after reboot

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#55]
● hhvm.service - HHVM HipHop Virtual Machine (FCGI)
   Loaded: loaded (/etc/systemd/system/hhvm.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-08-22 15:10:57 CEST; 5s ago
  Process: 656 ExecStart=/usr/local/bin/hhvm --config /etc/hhvm/server.ini --user nginx --mode daemon -vServer.Type=fastcgi -vServer.Port=9001 (code=exited, status=1/FAILURE)  Main PID: 656 (code=exited, status=1/FAILURE)

Aug 22 15:10:57 dw2.website.com hhvm[656]: [Mon Aug 22 15:10:57 2016] [hphp] [656:7f7e49e6b100:0:000010] [] BootStats: timezone_init done, took 0ms wall, 0ms cpu, 0 MB RSS
 Aug 22 15:10:57 dw2.website.com hhvm[656]: [Mon Aug 22 15:10:57 2016] [hphp] [656:7f7e49e6b100:0:000011] [] BootStats: xenon done, took 15ms wall, 7ms cpu, 3 MB RSS
 Aug 22 15:10:57 dw2.website.com hhvm[656]: [Mon Aug 22 15:10:57 2016] [hphp] [656:7f7e49e6b100:0:000012] [] BootStats: pcre_reinit done, took 1ms wall, 1ms cpu, -1 MB RSS 
Aug 22 15:10:57 dw2.website.com hhvm[656]: [Mon Aug 22 15:10:57 2016] [hphp] [656:7f7e49e6b100:0:000013] [] BootStats: onig_init done, took 0ms wall, 0ms cpu, 1 MB RSS 
Aug 22 15:10:57 dw2.website.com hhvm[656]: [Mon Aug 22 15:10:57 2016] [hphp] [656:7f7e49e6b100:0:000014] [] BootStats: xmlInitParser done, took 0ms wall, 0ms cpu, 0 MB RSS
 Aug 22 15:10:57 dw2.website.com hhvm[656]: [Mon Aug 22 15:10:57 2016] [hphp] [656:7f7e49e6b100:0:000015] [] Failed to initialize central HHBC repository:\n  Failed to open /var/run/hhvm/hhvm.hhbc: 14 - unable to open database file\n  Failed to open /var/cache/nginx/.hhvm.hhbc: 14 - unable to open database file\n Aug 22 15:10:57 dw2.website.com systemd[1]: hhvm.service: main process exited, code=exited, status=1/FAILURE Aug 22 15:10:57 dw2.website.com systemd[1]: Unit hhvm.service entered failed state.
Aug 22 15:10:57 dw2.website.com systemd[1]: Triggering OnFailure= dependencies of hhvm.service.
Aug 22 15:10:57 dw2.website.com systemd[1]: hhvm.service failed.

**Comment by magenx** [comment]
yes, forgot to configure hhvm service with proper user and repo path

**Comment by gladroger** [comment]
Reran the script on a fresh install this morning, hhvm service still fails after reboot.

**Comment by magenx** [comment]
it is not fixed yet
need to check

**Comment by magenx** [comment]
tested new changes, works ok
