### ISSUE TITLE
Image Optimization Script

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#56]
`IMAGES OPTIMIZATION SCRIPT
no crontab for myuser

  [InvalidArgumentException]
  There are no commands defined in the "deploy:mode" namespace.
  [InvalidArgumentException]
  There are no commands defined in the "setup:static-content" namespace.
`
Got no CSS in backend or in frontend, don't know if it's due to this issue.

**Comment by gladroger** [comment]
Manually ran

su user /bin/bash
/bin/bash -c "bin/magento deploy:mode:set developer && bin/magento cache:disable"
/bin/bash -c "bin/magento setup:static-content:deploy ${MAGE_LOCALE}"

CSS working after that.

**Comment by magenx** [comment]
this script is one way, if you run postconfig few times it will break some files.

**Comment by gladroger** [comment]
I can promise I didnt run postconfig several times. Got the same error message now. 
![image](https://cloud.githubusercontent.com/assets/1133729/17859563/6371ab5e-688a-11e6-87a9-92c63b6b616f.png)

**Comment by zorik01** [comment]
Same here: CentOS 7, build:1511
Script error-ed on first run, manual execution in terminal worked fine.

**Comment by magenx** [comment]
fixed
new script works ok
