### ISSUE TITLE
error importing crontab for brand new user

### ISSUE THREAD

**Issue by zorik01** [magenx/Magento-Automated-Server-Configuration-from-MagenX#58]
crontab -l -u ${MAGE_WEB_USER} > magecron 
the content of magecron = "no crontab for user ..."        

crontab -l -u ${MAGE_WEB_USER} > magecron
        echo "MAILTO="${MAGE_ADMIN_EMAIL}"" >> magecron
        echo "* * * * * php -c /etc/php.ini ${MAGE_WEB_ROOT_PATH}/bin/magento cron:run" >> magecron
	echo "* * * * * php -c /etc/php.ini ${MAGE_WEB_ROOT_PATH}/update/cron.php" >> magecron
	echo "* * * * * php -c /etc/php.ini ${MAGE_WEB_ROOT_PATH}/bin/magento setup:cron:run" >> magecron
        echo "5 8 * * 7 perl ${MAGE_WEB_ROOT_PATH}/mysqltuner.pl --nocolor 2>&1 | mailx -E -s \"MYSQLTUNER WEEKLY REPORT at ${HOSTNAME}\" ${MAGE_ADMIN_EMAIL}" >> magecron

when importing crontab:
magecron content = "
no crontab for user ...
    echo "* * * * * php -c /etc/php.ini ${MAGE_WEB_ROOT_PATH}/bin/magento cron:run" >> magecron
	echo "* * * * * php -c /etc/php.ini ${MAGE_WEB_ROOT_PATH}/update/cron.php" >> magecron
	echo "* * * * * php -c /etc/php.ini ${MAGE_WEB_ROOT_PATH}/bin/magento setup:cron:run" >> magecron
        echo "5 8 * * 7 perl ${MAGE_WEB_ROOT_PATH}/mysqltuner.pl --nocolor 2>&1 | mailx -E -s \"MYSQLTUNER WEEKLY REPORT at ${HOSTNAME}\" ${MAGE_ADMIN_EMAIL}
"
        crontab -u ${MAGE_WEB_USER} magecron
the line above gives syntax error and fails to create crontab for a given user
rm magecron

possible fix:
change line 1351: 
from: crontab -l -u ${MAGE_WEB_USER} > magecron
to:   crontab -l -u ${MAGE_WEB_USER}  | sed -i "s/no crontab for ${MAGE_WEB_USER}//g" > magecron

**Comment by magenx** [comment]
hi
this line was removed, 
cause crontab is empty anyway

**Comment by zorik01** [comment]
Thanks for the fix, closing the issue.

BTW: Huge thanks for a great job and sharing the code!!!
Let me know pls how can we contribute and make it even better.

-Z
