### ISSUE TITLE
MAGE_LOCALE & Currency

### ISSUE THREAD

**Issue by 3zzy** [magenx/Magento-Automated-Server-Configuration-from-MagenX#59]
Thanks for the wonderful script that does all the heavy lifting!

Just ran into a small issue:

```
---> Use up/down arrow keys then press enter to select MAGE_CURRENCY
./MASC-M-7-v2.sh: line 134: item: bad array subscript
                                 ./MASC-M-7-v2.sh: line 136: item: bad array subscript
./MASC-M-7-v2.sh: line 134: item: bad array subscript
                                 ./MASC-M-7-v2.sh: line 136: item: bad array subscript
```

up/down arrow keys do nothing. I'm on CentoOS 7 / Ec2

**Comment by magenx** [comment]
did you run all the script? did you change anything before installation?

**Comment by skmudabbir** [comment]
Hello 

This issue occurs when composer is giving error when we select from the menu magento > Select Magento 2, It says it will be downloaded to  newly created user home directory and then throws error > 
`bash: composer: command not found` 
When installing composer it creates a file(composer)  not a directory under  /usr/local/bin/, it does not move composer.phar to the location.and there when we do manual install of composer it gives error
`COMPOSER INSTALLATION ERROR`

When we ignore this and go to next steps the above bad array subscript error comes.

**Comment by magenx** [comment]
this is very strange error, probably still related to specific environment, networking or other connectivity issues. from our tests never had such problem.

**Comment by skmudabbir** [comment]
I used it on a fresh ec2 redhat 7 image which came without any additional modifications.

**Comment by magenx** [comment]
can you test it with this line to see more output:
`curl https://getcomposer.org/installer | php`

**Comment by skmudabbir** [comment]
Hello 

There is a similar error but this time it actually downloaded. 

I got this error

:`All settings correct for using Composer
Downloading...

Composer (version 1.4.1) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

bash: composer: command not found
`

Before it was not this much interaction.

**Comment by magenx** [comment]
on fresh linux installation it must be somethinf like this:

```
curl https://getcomposer.org/installer | php
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  298k  100  298k    0     0  1173k      0 --:--:-- --:--:-- --:--:-- 1170k
All settings correct for using Composer
Downloading...

Composer (version 1.4.1) successfully installed to: /root/composer.phar
Use it: php composer.phar


```
