### ISSUE TITLE
Fixing Permissions

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#61]
FIXING PERMISSIONS
chmod: cannot access ‘wesley.pl’: No such file or directory
chmod: cannot access ‘mysqltuner.pl’: No such file or directory
chmod: cannot access ‘n98-magerun2.phar’: No such file or directory

**Comment by magenx** [comment]
thank you for using this script and reporting issues back
some changes and commits are made after test.

**Comment by gladroger** [comment]
No, it's me that should be thanking you for this script. 

Thanks a lot

**Comment by mrlerch** [comment]
same here! I would like to thank you all for the script as well. It saves so much time!
