### ISSUE TITLE
Can't login into backend after installation

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#62]
Writing the correct user / password in the backend won't let me in. Tried flushing magento cache

**Comment by magenx** [comment]
there is an issue with hhvm and session compression
working to find a solution

**Comment by magenx** [comment]
there are no supported modules available.
for now configured with gzip

also looks like magento 2.1.1 with session handler

**Comment by gladroger** [comment]
Reran the script today, can login into admin but no css loaded.
