### ISSUE TITLE
Webmin Installation Package

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#63]
---> Start the Webmin Control Panel installation? [y/n][n]:y

                Installation of Webmin package:

     PROCESSING  ########

               WEBMIN INSTALLATION ERROR

---> Press [Enter] key to show menu

**Comment by magenx** [comment]
sure you can try to install it again, probably network issue

**Comment by gladroger** [comment]
Sorry, it works now.
