### ISSUE TITLE
missing ";"

### ISSUE THREAD

**Issue by rockdrigo** [magenx/Magento-Automated-Server-Configuration-from-MagenX#64]
| DOWNLOADING MAGENTO 1.9.2.4 |
-------------------------------------------------------------------------------------

---> Enter your domain name (without www.): mydomain.mx

--->  Magento 1.9.2.4 will be downloaded to:
--->  /home/mydomain/public_html
      DOWNLOADING MAGENTO  ####
chown: missing operand after ‘:’
Try 'chown --help' for more information.

**Comment by rockdrigo** [comment]
and not all the files are "chowned" :D 
maybe the error was on the 938 line

**Comment by magenx** [comment]
this is fixed now, but,
this file needs some updates.

**Comment by rockdrigo** [comment]
what kind of updates?? you dont recomend to use now for a production enviroment??

**Comment by magenx** [comment]
it is ready for production, just some cleanup for better configuration.

**Comment by rockdrigo** [comment]
-------------------------------------------------------------------------------------
POST-INSTALL CONFIGURATION
-------------------------------------------------------------------------------------

                CHANGING YOUR local.xml FILE WITH REDIS SESSIONS AND CACHE BACKEND

sed: can't read /home/mydomain/public_html/app/etc/local.xml: No such file or directory
sed: can't read /home/mydomain/public_html/app/etc/local.xml: No such file or directory

                DISABLING MAGENTO LOGS

sed: can't read /home/mydomain/public_html/app/etc/local.xml: No such file or directory

                CLEANING UP INDEXES LOCKS AND RUNNING RE-INDEX ALL

PHP Fatal error:  Uncaught Zend_Exception: dbModel read resource does not implement Zend_Db_Adapter_Abstract in /home/mydomain/public_html/lib/Varien/Data/Collection/Db.php:187
Stack trace:
#0 /home/mydomain/public_html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(134): Varien_Data_Collection_Db->setConnection(false)
#1 /home/mydomain/public_html/app/code/core/Mage/Core/Model/Config.php(1354): Mage_Core_Model_Resource_Db_Collection_Abstract->__construct(Array)
#2 /home/mydomain/public_html/app/code/core/Mage/Core/Model/Config.php(1386): Mage_Core_Model_Config->getModelInstance('index_resource/...', Array)
#3 /home/mydomain/public_html/app/Mage.php(491): Mage_Core_Model_Config->getResourceModelInstance('index/process_c...', Array)
#4 /home/mydomain/public_html/app/code/core/Mage/Index/Model/Indexer.php(85): Mage::getResourceModel('index/process_c...')
#5 /home/mydomain/public_html/app/code/core/Mage/Index/Model/Indexer.php(74): Mage_Index_Model_Indexer->getProcessesCollection()
#6 /home in /home/mydomain/public_html/lib/Varien/Data/Collection/Db.php on line 187





                PROFTPD CONFIGURATION
------> Press [Enter] key to continue

Usage: geoiplookup [-h] [-?] [-d custom_dir] [-f custom_file] [-v] [-i] [-l] <ipaddress|hostname>

Job for proftpd.service failed because the control process exited with error code. See "systemctl status proftpd.service" and "journalctl -xe" for details.

**Comment by magenx** [comment]
script was updated.
new features and settings.

**Comment by rockdrigo** [comment]
thanks, i will test in a few hours and if anything happends i will create a new issue ;D

thanks again!
