### ISSUE TITLE
Nginx Error Magento 1

### ISSUE THREAD

**Issue by gleert** [magenx/Magento-Automated-Server-Configuration-from-MagenX#65]
After installing the site doesn't load and nginx -t gives the following error:

nginx: [emerg] open() "/etc/nginx/conf_m1/export.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/magento.conf:54

How can I solve this?

**Comment by mrlerch** [comment]
Hi, happened to me too. Go to /etc/nginx/sites-available/magento.conf and just comment out the inclusion of header.conf and export.conf (for some odd reason they didn't install for me either.

That should allow you to start up nginx and install Magento.

You can also go to github and download the .conf files there. Good luck!



Martin

**Comment by magenx** [comment]
script was updated with new features and settings
