### ISSUE TITLE
local.xml error on POST-INSTALL CONFIGURATION for Magento v1

### ISSUE THREAD

**Issue by gleert** [magenx/Magento-Automated-Server-Configuration-from-MagenX#66]
POST-INSTALL CONFIGURATION

            CHANGING YOUR local.xml FILE WITH REDIS SESSIONS AND CACHE BACKEND

sed: can't read /home/mydomain/public_html/app/etc/local.xml: No such file or directory
sed: can't read /home/mydomain/public_html/app/etc/local.xml: No such file or directory

            DISABLING MAGENTO LOGS

sed: can't read /home/mydomain/public_html/app/etc/local.xml: No such file or directory

            CLEANING UP INDEXES LOCKS AND RUNNING RE-INDEX ALL

PHP Fatal error: Uncaught Zend_Exception: dbModel read resource does not implement Zend_Db_Adapter_Abstract in /home/mydomain/public_html/lib/Varien/Data/Collection/Db.php:187
Stack trace:
#0 /home/mydomain/public_html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(134): Varien_Data_Collection_Db->setConnection(false)
#1 /home/mydomain/public_html/app/code/core/Mage/Core/Model/Config.php(1354): Mage_Core_Model_Resource_Db_Collection_Abstract->__construct(Array)
#2 /home/mydomain/public_html/app/code/core/Mage/Core/Model/Config.php(1386): Mage_Core_Model_Config->getModelInstance('index_resource/...', Array)
#3 /home/mydomain/public_html/app/Mage.php(491): Mage_Core_Model_Config->getResourceModelInstance('index/process_c...', Array)
#4 /home/mydomain/public_html/app/code/core/Mage/Index/Model/Indexer.php(85): Mage::getResourceModel('index/process_c...')
#5 /home/mydomain/public_html/app/code/core/Mage/Index/Model/Indexer.php(74): Mage_Index_Model_Indexer->getProcessesCollection()
#6 /home in /home/mydomain/public_html/lib/Varien/Data/Collection/Db.php on line 187

**Comment by magenx** [comment]
magento is not installed,
there was an error.
