### ISSUE TITLE
Connection to Redis failed after 2 failures.

### ISSUE THREAD

**Issue by erosrb** [magenx/Magento-Automated-Server-Configuration-from-MagenX#67]
Magento M1 Report:

`a:4:{i:0;s:44:"Connection to Redis failed after 2 failures.";i:1;s:1340:"#0 /home/meuposternovo/public_html/lib/Credis/Client.php(439): Credis_Client->connect()
#1 /home/meuposternovo/public_html/lib/Credis/Client.php(725): Credis_Client->connect()
#2 /home/meuposternovo/public_html/lib/Credis/Client.php(599): Credis_Client->__call()
#3 /home/meuposternovo/public_html/lib/Cm/Cache/Backend/Redis.php(135): Credis_Client->select()
#4 /home/meuposternovo/public_html/lib/Zend/Cache.php(153): Cm_Cache_Backend_Redis->__construct()
#5 /home/meuposternovo/public_html/lib/Zend/Cache.php(94): Zend_Cache::_makeBackend()
#6 /home/meuposternovo/public_html/app/code/core/Mage/Core/Model/Cache.php(137): Zend_Cache::factory()
#7 /home/meuposternovo/public_html/app/code/core/Mage/Core/Model/Config.php(1354): Mage_Core_Model_Cache->__construct()
#8 /home/meuposternovo/public_html/app/Mage.php(463): Mage_Core_Model_Config->getModelInstance()
#9 /home/meuposternovo/public_html/app/code/core/Mage/Core/Model/App.php(412): Mage::getModel()
#10 /home/meuposternovo/public_html/app/code/core/Mage/Core/Model/App.php(306): Mage_Core_Model_App->_initCache()
#11 /home/meuposternovo/public_html/app/code/core/Mage/Core/Model/App.php(348): Mage_Core_Model_App->baseInit()
#12 /home/meuposternovo/public_html/app/Mage.php(684): Mage_Core_Model_App->run()
#13 /home/meuposternovo/public_html/index.php(83): Mage::run()
#14 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";}`

Magento Log:

`2016-09-12T01:32:54+00:00 ERR (3): Warning: Failed connecting to redis server at 127.0.0.1: Connection refused  in  on line 0`

any ideas?

temporary solution:

Delete this part from public_html/app/etc/local.xml file

Line 51
```
`    <cache> 
        <backend>Cm_Cache_Backend_Redis</backend> 
        <backend_options> 
          <default_priority>10</default_priority> 
          <auto_refresh_fast_cache>1</auto_refresh_fast_cache> 
            <server>127.0.0.1</server> 
            <port>6380</port> 
            <persistent><![CDATA[db1]]></persistent> 
            <database>1</database> 
            <password></password> 
            <force_standalone>0</force_standalone> 
            <connect_retries>1</connect_retries> 
            <read_timeout>10</read_timeout> 
            <automatic_cleaning_factor>0</automatic_cleaning_factor> 
            <compress_data>1</compress_data> 
            <compress_tags>1</compress_tags> 
            <compress_threshold>204800</compress_threshold> 
            <compression_lib>gzip</compression_lib> 
        </backend_options> 
    </cache>`
```

**Comment by magenx** [comment]
make sure you have readable /etc/redis-63*  file
`chmod 644 /etc/redis-63*`

it was fixed lately.
