### ISSUE TITLE
Fresh install Cannot Visit Cache Management Page in the admin

### ISSUE THREAD

**Issue by atrixtech** [magenx/Magento-Automated-Server-Configuration-from-MagenX#68]
Fresh install on a new droplet worked great for centos 7 on Digital Ocean.  It was slow so I tried to go to the cache management, and I get the following errors:

```
1 exception(s):
Exception #0 (Exception): Warning: Parameter 4 to Magento\Framework\Filter\Truncate::__construct() expected to be a reference, value given in /home/redacted/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

Exception #0 (Exception): Warning: Parameter 4 to Magento\Framework\Filter\Truncate::__construct() expected to be a reference, value given in /home/redacted/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93
#0 /home/redacted/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Framework\App\ErrorHandler->handler()
#1 /home/redacted/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#2 /home/redacted/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#3 /home/redacted/public_html/vendor/magento/framework/Filter/AbstractFactory.php(90): Magento\Framework\ObjectManager\ObjectManager->create()
#4 /home/redacted/public_html/vendor/magento/framework/Filter/FilterManager.php(87): Magento\Framework\Filter\AbstractFactory->createFilter()
#5 /home/redacted/public_html/vendor/magento/framework/Filter/FilterManager.php(133): Magento\Framework\Filter\FilterManager->createFilterInstance()
#6 /home/redacted/public_html/vendor/magento/module-backend/Block/Widget/Grid/Column/Renderer/Longtext.php(32): Magento\Framework\Filter\FilterManager->__call()
#7 /home/redacted/public_html/vendor/magento/module-backend/Block/Widget/Grid/Column.php(276): Magento\Backend\Block\Widget\Grid\Column\Renderer\Longtext->render()
#8 /home/redacted/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/column_set.phtml(113): Magento\Backend\Block\Widget\Grid\Column->getRowField()
#9 /home/redacted/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#10 /home/redacted/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#11 /home/redacted/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#12 /home/redacted/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#13 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#14 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#15 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#16 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#17 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#18 /home/redacted/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement()
#19 /home/redacted/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml(133): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#20 /home/redacted/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#21 /home/redacted/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#22 /home/redacted/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#23 /home/redacted/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#24 /home/redacted/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#25 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#26 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#27 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#28 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#29 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#30 /home/redacted/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement()
#31 /home/redacted/public_html/vendor/magento/module-backend/Block/Widget/Grid/Container.php(118): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#32 /home/redacted/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/container.phtml(13): Magento\Backend\Block\Widget\Grid\Container->getGridHtml()
#33 /home/redacted/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#34 /home/redacted/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#35 /home/redacted/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#36 /home/redacted/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#37 /home/redacted/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#38 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#39 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#40 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#41 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#42 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#43 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#44 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#45 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#46 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#47 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#48 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#49 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#50 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#51 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#52 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#53 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#54 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#55 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#56 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#57 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#58 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#59 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#60 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#61 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#62 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#63 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#64 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#65 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#66 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#67 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#68 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#69 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#70 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#71 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#72 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#73 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#74 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#75 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#76 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#77 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#78 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#79 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#80 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#81 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#82 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#83 /home/redacted/public_html/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement()
#84 /home/redacted/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#85 /home/redacted/public_html/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#86 /home/redacted/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render()
#87 /home/redacted/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult()
#88 /home/redacted/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#89 /home/redacted/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#90 /home/redacted/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run()
#91 {main}


```

Did this on the command line:
```
php bin/magento cache:enable
Changed cache status:
                        config: 0 -> 1
                        layout: 0 -> 1
                    block_html: 0 -> 1
                   collections: 0 -> 1
                    reflection: 0 -> 1
                        db_ddl: 0 -> 1
                           eav: 0 -> 1
         customer_notification: 0 -> 1
                     full_page: 0 -> 1
            config_integration: 0 -> 1
        config_integration_api: 0 -> 1
                     translate: 0 -> 1
             config_webservice: 0 -> 1
Cleaned cache types:
config
layout
block_html
collections
reflection
db_ddl
eav
customer_notification
full_page
config_integration
config_integration_api
translate
config_webservice
```

Speed is greatly improved, but still can't access Cache Management.

**Comment by atrixtech** [comment]
I worked a lot on this, then ended up turning off hhvm, and still not fixing it but at least getting logging to work.  I then tried turning on production mode and it killed the css files and broke half way, so I rebuilt the droplet about 3 more times trying different install methods, and finally with the version you updated today and installing without hhvm or varnish it worked properly.  Thanks for this great script it did save me a lot of work, but for magento 2 maybe disable varnish since it wasn't used anyway and I don't think magento 2 and hhvm are playing totally well together.

**Comment by magenx** [comment]
there is probably issue with different modes, cache and deployed files...
but per official documentation magento 2 works with hhvm 100%. (not sure if it properly tested)

dont forget that by default hhvm works as php 5.6, you need to change few parameters to make it work as php 7.0.

**Comment by gladroger** [comment]
Clean install today, got a similar error

`1 exception(s):
Exception #0 (Exception): Warning: Parameter 4 to Magento\Framework\Filter\Truncate::__construct() expected to be a reference, value given in /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

Exception #0 (Exception): Warning: Parameter 4 to Magento\Framework\Filter\Truncate::__construct() expected to be a reference, value given in /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93
#0 /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(93): Magento\Framework\App\ErrorHandler->handler()
#1 /home/dev/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(89): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject()
#2 /home/dev/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create()
#3 /home/dev/public_html/vendor/magento/framework/Filter/AbstractFactory.php(90): Magento\Framework\ObjectManager\ObjectManager->create()
#4 /home/dev/public_html/vendor/magento/framework/Filter/FilterManager.php(87): Magento\Framework\Filter\AbstractFactory->createFilter()
#5 /home/dev/public_html/vendor/magento/framework/Filter/FilterManager.php(133): Magento\Framework\Filter\FilterManager->createFilterInstance()
#6 /home/dev/public_html/vendor/magento/module-backend/Block/Widget/Grid/Column/Renderer/Longtext.php(32): Magento\Framework\Filter\FilterManager->__call()
#7 /home/dev/public_html/vendor/magento/module-backend/Block/Widget/Grid/Column.php(276): Magento\Backend\Block\Widget\Grid\Column\Renderer\Longtext->render()
#8 /home/dev/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/column_set.phtml(113): Magento\Backend\Block\Widget\Grid\Column->getRowField()
#9 /home/dev/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#10 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#11 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#12 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework\View\Element\Template->_toHtml()
#13 /home/dev/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#14 /home/dev/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#15 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#16 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#17 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#18 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement()
#19 /home/dev/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid.phtml(133): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#20 /home/dev/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#21 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#22 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#23 /home/dev/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#24 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#25 /home/dev/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#26 /home/dev/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#27 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#28 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#29 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#30 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(499): Magento\Framework\View\Layout\Interceptor->renderElement()
#31 /home/dev/public_html/vendor/magento/module-backend/Block/Widget/Grid/Container.php(118): Magento\Framework\View\Element\AbstractBlock->getChildHtml()
#32 /home/dev/public_html/vendor/magento/module-backend/view/adminhtml/templates/widget/grid/container.phtml(13): Magento\Backend\Block\Widget\Grid\Container->getGridHtml()
#33 /home/dev/public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#34 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render()
#35 /home/dev/public_html/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView()
#36 /home/dev/public_html/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#37 /home/dev/public_html/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Backend\Block\Template->_toHtml()
#38 /home/dev/public_html/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#39 /home/dev/public_html/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock()
#40 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#41 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#42 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#43 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#44 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#45 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#46 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#47 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#48 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#49 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#50 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#51 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#52 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#53 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#54 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#55 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#56 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#57 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#58 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#59 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#60 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#61 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#62 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#63 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#64 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#65 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#66 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#67 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#68 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#69 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#70 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#71 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#72 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#73 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#74 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#75 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#76 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#77 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#78 /home/dev/public_html/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement()
#79 /home/dev/public_html/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer()
#80 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement()
#81 /home/dev/public_html/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement()
#82 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement()
#83 /home/dev/public_html/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement()
#84 /home/dev/public_html/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#85 /home/dev/public_html/vendor/magento/framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()
#86 /home/dev/public_html/vendor/magento/framework/View/Result/Layout.php(164): Magento\Framework\View\Result\Page->render()
#87 /home/dev/public_html/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult()
#88 /home/dev/public_html/vendor/magento/framework/App/Http.php(139): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#89 /home/dev/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#90 /home/dev/public_html/pub/index.php(37): Magento\Framework\App\Bootstrap->run()
#91 {main}`

During "config" 
  [CredisException]
  read error on connection

......................................................................

  [RedisException]
  read error on connection
