### ISSUE TITLE
Had to disable redis, broke going into production mode

### ISSUE THREAD

**Issue by atrixtech** [magenx/Magento-Automated-Server-Configuration-from-MagenX#69]
Magento is working great if I disable redis but with it enabled l get breakage every time I try to go production.

The error's are like this:

```

  [CredisException]
  protocol error, got '\' as reply type byte


  [RedisException]
  protocol error, got '\' as reply type byte


  [RedisException]
  protocol error, got '\' as reply type byte


  [RedisException]
  protocol error, got 's' as reply type byte


  [RedisException]
  protocol error, got 'a' as reply type byte


  [CredisException]
  socket error on read socket


  [RedisException]
  socket error on read socket

```

It appears related to stuff like this reported several times but all the ones I looked at the fixes didn't work;
https://github.com/phpredis/phpredis/issues/831
https://github.com/colinmollenhour/Cm_Cache_Backend_Redis/issues/97
https://github.com/phpredis/phpredis/issues/614
https://github.com/phpredis/phpredis/issues/52
https://github.com/phpredis/phpredis/issues/369
https://github.com/phpredis/phpredis/issues/343
https://github.com/phpredis/phpredis/pull/13
https://xenforo.com/community/threads/zend-redis-cache.91023/page-5#post-1030967

It seems a really common issue to redis which makes me not think much of redis at the moment, I guess even functioning well it does this on high load?  In any case I disabled it on my install for now and hope this helps you make this script even more stable and better thanks for your time :D

**Comment by magenx** [comment]
this will be tested.

**Comment by magenx** [comment]
settings now updated.
it should work with redis and php-fpm.

hhvm disabled (only for testing) due to incompatibility...

**Comment by atrixtech** [comment]
Thanks, I copied your change to set persistent to an empty string and it seems to have worked without reinstall, thank you for the hard work, closing issue.
