### ISSUE TITLE
syntax error nearby unsexpected symbol 'else'

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-Automated-Server-Configuration-from-MagenX#70]
For Magento 1 getting the following error at the beginning after ssh and terms;

MASC-M-7-v2.sh: line 1670: syntax error nearby unsexpected symbol 'else'
MASC-M-7-v2.sh: line 1670: `    else'

**Comment by magenx** [comment]
its fixed now,
there was a typo
