### ISSUE TITLE
Repository installation error

### ISSUE THREAD

**Issue by jorgb90** [magenx/Magento-Automated-Server-Configuration-from-MagenX#71]
![10 08 46](https://cloud.githubusercontent.com/assets/7294081/18702789/97122504-7fe3-11e6-9a70-38f565f54e6b.png)

New Percona rep; https://www.percona.com/redir/downloads/percona-release/redhat/latest/percona-release-0.1-4.noarch.rpm

**Comment by magenx** [comment]
thank you for help.
