### ISSUE TITLE
SSL Letsencrypt autogenerate IPv6 and enable SSL after install

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#75]
I'm running behind a firewall. Letsencrypt during install fails and displays a ipv6 address. 

LETSENCRYPT SSL CERTIFICATE REQUEST
DNS A record and your servers IP address do not match
Your servers ip address 192.168.11.19

Domain dev.mydomain.com resolves to fe80::20c:29ff:fef7:fd
Please change your DNS A record to this servers IP address  and run this command later: /usr/bin/certbot certonly --standalone --email admin@dev.mydomain.com -d dev.mydomain.com -d www.dev.mydomain.com

If I run the exact command after install "/usr/bin/certbot certonly --standalone --email admin@dev.mydomain.com -d dev.mydomain.com -d" it works. 

What must I do to enable SSL afterwards? 

I have uncommented the following in magento2.conf
listen 443 ssl http2 reuseport;
ssl_certificate     /etc/letsencrypt/live/dev.mydomain.com/fullchain.pem; 
ssl_certificate_key /etc/letsencrypt/live/dev.mydomain.com/privkey.pem;
Restarted nginx but the site is currently redirecting looping forever.

**Comment by magenx** [comment]
loop is because you need to change in magento2.conf first server block.

**Comment by gladroger** [comment]
Thanks,

Can you please give me an example? I can't figure out what I'm doing wrong. 

Current config http://pastebin.com/nmBqXnDa

**Comment by magenx** [comment]
line 18-29:
```
## www redirect
#server {
#        listen 80;
#       listen 443 ssl http2;
#    server_name dev.devdomain.com;
#    return 301 $scheme://www.dev.devdomain.com$request_uri;
#}
 
server {
        listen 80 reuseport;
        listen 443 ssl http2 reuseport;
    server_name dev.devdomain.com;
```

**Comment by gladroger** [comment]
I have commented out the first section and removed the www. from the second server block but I'm still stuck in a loop after restarting. It might not be nginx that is redirecting between https and http.

I must keep the www. in the server_name in the server block since magentos base url is configured with www. 

I'm currently trying test different configs.

**Comment by gladroger** [comment]
I'm sorry but I can't get it to work and I'm really frustrated at the moment. 

Nginx is throwing 302 all over in the access.log 
`192.168.31.2 - - [01/Oct/2016:12:15:13 +0200] "GET / HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36" - "d70a31cafcc89b97c2ee82df85779491"`

Current http://pastebin.com/ZPendfvG

**Comment by magenx** [comment]
please paste here redirect headers.
probably you need to make the same domain name in database and nginx config

**Comment by gladroger** [comment]
Redirect headers?

Removed the www. in the database, flushed the cache via bin/magento but still redirecting loop.

**Comment by gladroger** [comment]
Got it working by running
"bin/magento setup:store-config:set --base-url-secure="https://dev.devdomain.com/"

Also Chrome also messed everything up, going to chrome://net-internals/#hsts
and deleting all old information on the domain. 

I'm closing this issue but I don't see why the auto generation of letsencrypt in the script does not resolve my external ip instead of internal ip and failing.
