### ISSUE TITLE
Job for nginx.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by corpsysgit** [magenx/Magento-Automated-Server-Configuration-from-MagenX#76]
Error in nginx start:

Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

Thanks for help!

**Comment by corpsysgit** [comment]
nginx: [emerg] invalid parameter "/32" in /etc/nginx/conf_m1/phpmyadmin.conf:6

**Comment by magenx** [comment]
this variable was fixed

**Comment by corpsysgit** [comment]
Thanks for job!

**Comment by Skudetto** [comment]
This error is present again in the current version

**Comment by mouad717** [comment]
Hi, This error is present again in the current version too

**Comment by diego-goulart** [comment]
Hi, This error is present again !

**Comment by magenx** [comment]
what you get when you type:
```
bash --version
cat /etc/redhat-release
echo ${SSH_CLIENT%% *}
```

**Comment by diego-goulart** [comment]
bash --version
`GNU bash, version 4.2.46(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`

cat /etc/redhat-release
`CentOS Linux release 7.2.1511 (Core)`

echo ${SSH_CLIENT%% *}
`177.41.154.137`

**Comment by kotAPI** [comment]
Similar error when I tried to restart my nginx server with uwsgi and django.

`/etc/nginx/sites-available# sudo service nginx restart 
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
`

**Comment by dmumladze** [comment]
I've got v1.13.8 and same error

[root@localhost ~]# `systemctl restart nginx.service`

`Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.`
