### ISSUE TITLE
The download magento2 is not working

### ISSUE THREAD

**Issue by marcuspitu** [magenx/Magento-Automated-Server-Configuration-from-MagenX#78]
There is no files on the public_html

After type (magento) receive this: bash: composer: command not found
![sem titulo](https://cloud.githubusercontent.com/assets/4326788/19404853/b95f81e4-9247-11e6-97f0-69a8eba4992b.png)

**Comment by magenx** [comment]
probably there was composer installation error

**Comment by corpsysgit** [comment]
In my case the same and the composer is installed.

**Comment by fladventurerob** [comment]
I am having the exact same issue and composer installed and ran fine
