### ISSUE TITLE
nginx: [emerg] invalid parameter "/32" in /etc/nginx/conf_m1/phpmyadmin.conf:6

### ISSUE THREAD

**Issue by Skudetto** [magenx/Magento-Automated-Server-Configuration-from-MagenX#81]
This error is present in the current version:

nginx: [emerg] invalid parameter "/32" in /etc/nginx/conf_m1/phpmyadmin.conf:6

**Comment by gsdsd** [comment]
Closed without solution ?

**Comment by magenx** [comment]
i dont understand this message,
i need to know at least OS version , ssh version and virtualizator if any

**Comment by gsdsd** [comment]
Ok it seems that I have the same error message as the user above and I put this comment because you have closed this ticket without giving a public solution.

> nginx: [emerg] invalid parameter "/32" in /etc/nginx/conf_m2/phpmyadmin.conf:6

VM Virtualized with LibVirt on Ubuntu 14:

>  CentOS Linux release 7.3.1611 (Core)

SSH:

> OpenSSH_6.6.1p1
> OpenSSL 1.0.1e-fips 

Regards,

GsdSd

**Comment by gsdsd** [comment]
ok i'm open new ticket...
