### ISSUE TITLE
Redis not working Magento 1.x

### ISSUE THREAD

**Issue by MartinWierenga** [magenx/Magento-Automated-Server-Configuration-from-MagenX#82]
When installing Magento 1.x with this script and installed Memcached & Redis the file Cm_RedisSession.xml is not set correctly. The `<active>` is still on false which leads to problems logging into Admin Dashboard.

**Comment by magenx** [comment]
thank you 
its fixed now

**Comment by MartinWierenga** [comment]
Thanks, I will test it.
I did come across another issue, the Magento Admin Dashboard doesn't show properly. The CSS isn't correct, when logged in it's not loading CSS but I don't know yet where the issue exactly is coming from.
I use a CentOS7 install fully updated with only your script and MariaDB instead of Percona. Btw, also http and https adding in firewalld would be great but assume that's something bit harder due all different configs.

**Comment by MartinWierenga** [comment]
Btw, opening those ports for http and https helps with LetsEncrypt right?
