### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by victooooor** [magenx/Magento-Automated-Server-Configuration-from-MagenX#83]
Hi, i newbie, but follow all steps and error found.

nginx use web root 
/usr/share/nginx/html/index.html

but downloading magento use web root
/home/hostname/public_html

after this, lets encrypter bug plash

please check, i love this script  <3

**Comment by magenx** [comment]
this script only works on empty server.
also letsencrypt prints errors and suggests a possible fix.

**Comment by victooooor** [comment]
Yeah, i know.
I try install on empty server.
if you can remote access my computer i loved  <3
have teamviewer,  or i can send u my empty droplet and you see. whatever
thank you bro

**Comment by magenx** [comment]
> nginx use web root
> /usr/share/nginx/html/index.html

this is not a part of this script

**Comment by victooooor** [comment]
i'll make a video!
