### ISSUE TITLE
Redis has been installed

### ISSUE THREAD

**Issue by gladroger** [magenx/Magento-Automated-Server-Configuration-from-MagenX#84]
Trying a new clean dev install. 

`REDIS HAS BEEN INSTALLED
cp: cannot stat ‘/usr/lib/systemd/system/searchd.service’: No such file or directory
sed: can't read /etc/systemd/system/searchd.service: No such file or directory
sed: can't read /etc/systemd/system/searchd.service: No such file or directory`

**Comment by magenx** [comment]
looks like issue with sphinx search package installation
fixed for now


thank you
