### ISSUE TITLE
Some missing library dependencies for webmin, maldet and csf

### ISSUE THREAD

**Issue by webshopessentials** [magenx/Magento-Automated-Server-Configuration-from-MagenX#85]
First of all, this script looks very promoting for fully automating the deployment of a Magento 2 webshop.
I've tested this script on my VPS and ran into some missing dependencies:

- Library required for webmin (_WARNING* URLGET set to use LWP but perl module is not installed, reverting to HTTP::Tiny_): perl-libwww-perl
- Library required for maldet: ed
- Library required for csf: bind-utils
- Library required for csf update: perl-LWP-Protocol-https
- Optional library required when you want to make use of webmin historical stats: perl-rrdtool rrdtool

So I now run the following statement first before running this script:

`yum -y install perl-libwww-perl  ed inotify-tools bind-utils perl-LWP-Protocol-https perl-rrdtool rrdtool `

Can you please add the missing dependencies in this script?

**Comment by magenx** [comment]
i dont see any issues.
all required modules and packages should be installed from line 453 to 456

**Comment by webshopessentials** [comment]
The dependency issues become visible when you click around in webmin, for example to update packages or administer csf.
I will post the exact issue with maldet in a day or so as I am planning to test my runbook again.

**Comment by webshopessentials** [comment]
Strange, but I didn't run into the dependency issues anymore when going through all the steps I've documented.
Only the dependency for perl-rrdtool rrdtool showed up but that is because of historical stats module for webmin.
Therefore closing this issue.
