### ISSUE TITLE
Some errors occurred during SSL certificate creation

### ISSUE THREAD

**Issue by diego-goulart** [magenx/Magento-Automated-Server-Configuration-from-MagenX#89]
LETSENCRYPT SSL CERTIFICATE REQUEST

		DNS A record and your servers IP address do not match
		Your servers ip address 192.0.1.170
		Domain triup.com.br resolves to 52.67.121.0
		Please change your DNS A record to this servers IP address
		and run this command later: /usr/bin/certbot certonly --agree-tos --email admin@triup.com.br --webroot -w /home/triup/public_html -d triup.com.br -d www.triup.com.br

**Comment by magenx** [comment]
please do not spam here.

**Comment by diego-goulart** [comment]
Sorry was not the intention. I just wanted to separate the issues on different issues

**Comment by magenx** [comment]
error message is self-explanatory.
