### ISSUE TITLE
Error in initial FTP server configuration

### ISSUE THREAD

**Issue by diego-goulart** [magenx/Magento-Automated-Server-Configuration-from-MagenX#91]
Usage: geoiplookup [-h] [-?] [-d custom_dir] [-f custom_file] [-v] [-i] [-l] <ipaddress|hostname>

Job for proftpd.service failed because the control process exited with error code. See "systemctl status proftpd.service" and "journalctl -xe" for details.

**Comment by magenx** [comment]
please do not spam here.

**Comment by diego-goulart** [comment]
Sorry was not the intention. I just wanted to separate the issues on different issues.

**Comment by diego-goulart** [comment]
Is not self-explanatory to me. Can you help?

**Comment by magenx** [comment]
when you run server installation you need at least know what error message means and how to debug it.
you probably have some specific issues with your environment.

**Comment by diego-goulart** [comment]
OK brother. Thank's for your time.
