### ISSUE TITLE
Invalid parameter /32

### ISSUE THREAD

**Issue by tmccaff** [magenx/Magento-Automated-Server-Configuration-from-MagenX#93]
Getting the following error:
Invalid parameter "/32" in /etc/nginx/conf_m1/phpmyadmin.conf

**Comment by magenx** [comment]
there must be your ip address x.x.x.x/32;
not sure why this variable is empty.

what is your ssh version?

**Comment by tmccaff** [comment]
That's why I don't use SSH personally. I guess I can just delete that line. I have to figure out why it takes so long to load especially the backend. Thanks
