### ISSUE TITLE
Should add SELinux instead of disabled

### ISSUE THREAD

**Issue by tmccaff** [magenx/Magento-Automated-Server-Configuration-from-MagenX#94]
it's kind of a security risk having SELinux disabled

the parameters are:

setsebool -P httpd_enable_homedirs 1
setsebool -P httpd_setrlimit 1
chcon -R -t httpd_sys_content_t /home/user/public_html

that should do it..

**Comment by magenx** [comment]
if you prove that these 3 commands add a great security and protection i will use selinux...

**Comment by tmccaff** [comment]
I am going to test it today

**Comment by tmccaff** [comment]
ok I would have it checked for SELinux:permissive instead of disabled and no errors go to enforcing:

Extra packages to install:
yum install policycoreutils-python setroubleshoot setools

to check for errors:
sealert -a /var/log/audit/audit.log | less

the following commands should get you good into enforcing:
setsebool -P httpd_setrlimit 1
setsebool -P httpd_can_network_connect 1
setsebool -P httpd_enable_homedirs 1

The following policys need to be added:
for redis server read permission, etc:
ausearch -c 'redis-server' --raw | audit2allow -M my-redisserver
semodule -i my-redisserver.pp

For nginx read permission:
ausearch -c 'nginx' --raw | audit2allow -M my-nginx
semodule -i my-nginx.pp

need to set public content to index.php 
semanage fcontext -a -t public_content_t '/pathtowebroot/index.php'
restorecon -v '/pathtowebroot/index.php'

for php-fpm read and write access
ausearch -c 'php-fpm' --raw | audit2allow -M my-phpfpm   
semodule -i my-phpfpm.pp

for MySQL:
ausearch -c 'mysqld_safe' --raw | audit2allow -M my-mysqldsafe
semodule -i my-mysqldsafe.pp

that should do it; now for Magento Connect may need to add extra's; I don't use that so I haven't tested that.

Let me know if you experience any problems..

**Comment by tmccaff** [comment]
I haven't tested it with varnish and hhvm yet which I am doing now.

**Comment by tmccaff** [comment]
need to add another parameter I forgot:
semanage fcontext -a -t redis_var_lib_t '/var/lib/redis-6379'
restorecon -v /var/lib/redis-6379

**Comment by tmccaff** [comment]
I added this to my copy:

tmccaff/Magento-Server-Configuration I forget how to issue a pull request it's been a long time.

I would test this and see if any problems arise; permissive mode usually don't block access it gives warnings that if we go enforcing will block access.
